<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance_transaction.proto

namespace Yinge\Grpc\Finance\SplitRequest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finance.SplitRequest.SplitSubOrder</code>
 */
class SplitSubOrder extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 SpuId = 1;</code>
     */
    protected $SpuId = 0;
    /**
     * Generated from protobuf field <code>int64 FactoryId = 2;</code>
     */
    protected $FactoryId = 0;
    /**
     * Generated from protobuf field <code>int64 ExpressId = 3;</code>
     */
    protected $ExpressId = 0;
    /**
     * Generated from protobuf field <code>int64 ProduceCost = 4;</code>
     */
    protected $ProduceCost = 0;
    /**
     * Generated from protobuf field <code>bool IsCurrent = 5;</code>
     */
    protected $IsCurrent = false;
    /**
     * Generated from protobuf field <code>int64 SubOrderId = 6;</code>
     */
    protected $SubOrderId = 0;
    /**
     * Generated from protobuf field <code>string Remark = 7;</code>
     */
    protected $Remark = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $SpuId
     *     @type int|string $FactoryId
     *     @type int|string $ExpressId
     *     @type int|string $ProduceCost
     *     @type bool $IsCurrent
     *     @type int|string $SubOrderId
     *     @type string $Remark
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Finance\GPBMetadata\FinanceTransaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 SpuId = 1;</code>
     * @return int|string
     */
    public function getSpuId()
    {
        return $this->SpuId;
    }

    /**
     * Generated from protobuf field <code>int64 SpuId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSpuId($var)
    {
        GPBUtil::checkInt64($var);
        $this->SpuId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 FactoryId = 2;</code>
     * @return int|string
     */
    public function getFactoryId()
    {
        return $this->FactoryId;
    }

    /**
     * Generated from protobuf field <code>int64 FactoryId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFactoryId($var)
    {
        GPBUtil::checkInt64($var);
        $this->FactoryId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 ExpressId = 3;</code>
     * @return int|string
     */
    public function getExpressId()
    {
        return $this->ExpressId;
    }

    /**
     * Generated from protobuf field <code>int64 ExpressId = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpressId($var)
    {
        GPBUtil::checkInt64($var);
        $this->ExpressId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 ProduceCost = 4;</code>
     * @return int|string
     */
    public function getProduceCost()
    {
        return $this->ProduceCost;
    }

    /**
     * Generated from protobuf field <code>int64 ProduceCost = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setProduceCost($var)
    {
        GPBUtil::checkInt64($var);
        $this->ProduceCost = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool IsCurrent = 5;</code>
     * @return bool
     */
    public function getIsCurrent()
    {
        return $this->IsCurrent;
    }

    /**
     * Generated from protobuf field <code>bool IsCurrent = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsCurrent($var)
    {
        GPBUtil::checkBool($var);
        $this->IsCurrent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 SubOrderId = 6;</code>
     * @return int|string
     */
    public function getSubOrderId()
    {
        return $this->SubOrderId;
    }

    /**
     * Generated from protobuf field <code>int64 SubOrderId = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSubOrderId($var)
    {
        GPBUtil::checkInt64($var);
        $this->SubOrderId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Remark = 7;</code>
     * @return string
     */
    public function getRemark()
    {
        return $this->Remark;
    }

    /**
     * Generated from protobuf field <code>string Remark = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setRemark($var)
    {
        GPBUtil::checkString($var, True);
        $this->Remark = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(SplitSubOrder::class, \Yinge\Grpc\Finance\SplitRequest_SplitSubOrder::class);

