<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qpm.proto

namespace Yinge\Grpc\Qpm;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Qpm.FactoryRule</code>
 */
class FactoryRule extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 skuId = 1;</code>
     */
    protected $skuId = 0;
    /**
     * Generated from protobuf field <code>int32 factoryId = 2;</code>
     */
    protected $factoryId = 0;
    /**
     * Generated from protobuf field <code>string factoryName = 3;</code>
     */
    protected $factoryName = '';
    /**
     * Generated from protobuf field <code>float rate = 4;</code>
     */
    protected $rate = 0.0;
    /**
     * Generated from protobuf field <code>string produceCode = 5;</code>
     */
    protected $produceCode = '';
    /**
     * Generated from protobuf field <code>string produceName = 6;</code>
     */
    protected $produceName = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $skuId
     *     @type int $factoryId
     *     @type string $factoryName
     *     @type float $rate
     *     @type string $produceCode
     *     @type string $produceName
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Qpm\GPBMetadata\Qpm::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 skuId = 1;</code>
     * @return int
     */
    public function getSkuId()
    {
        return $this->skuId;
    }

    /**
     * Generated from protobuf field <code>int32 skuId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSkuId($var)
    {
        GPBUtil::checkInt32($var);
        $this->skuId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 factoryId = 2;</code>
     * @return int
     */
    public function getFactoryId()
    {
        return $this->factoryId;
    }

    /**
     * Generated from protobuf field <code>int32 factoryId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setFactoryId($var)
    {
        GPBUtil::checkInt32($var);
        $this->factoryId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string factoryName = 3;</code>
     * @return string
     */
    public function getFactoryName()
    {
        return $this->factoryName;
    }

    /**
     * Generated from protobuf field <code>string factoryName = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setFactoryName($var)
    {
        GPBUtil::checkString($var, True);
        $this->factoryName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float rate = 4;</code>
     * @return float
     */
    public function getRate()
    {
        return $this->rate;
    }

    /**
     * Generated from protobuf field <code>float rate = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setRate($var)
    {
        GPBUtil::checkFloat($var);
        $this->rate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string produceCode = 5;</code>
     * @return string
     */
    public function getProduceCode()
    {
        return $this->produceCode;
    }

    /**
     * Generated from protobuf field <code>string produceCode = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setProduceCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->produceCode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string produceName = 6;</code>
     * @return string
     */
    public function getProduceName()
    {
        return $this->produceName;
    }

    /**
     * Generated from protobuf field <code>string produceName = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setProduceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->produceName = $var;

        return $this;
    }

}

