<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qpm.proto

namespace Yinge\Grpc\Qpm;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Qpm.FactoryExpressItem</code>
 */
class FactoryExpressItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string express = 1;</code>
     */
    protected $express = '';
    /**
     * Generated from protobuf field <code>string code = 2;</code>
     */
    protected $code = '';
    /**
     * Generated from protobuf field <code>int32 rate = 3;</code>
     */
    protected $rate = 0;
    /**
     * Generated from protobuf field <code>int32 id = 4;</code>
     */
    protected $id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $express
     *     @type string $code
     *     @type int $rate
     *     @type int $id
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Qpm\GPBMetadata\Qpm::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string express = 1;</code>
     * @return string
     */
    public function getExpress()
    {
        return $this->express;
    }

    /**
     * Generated from protobuf field <code>string express = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setExpress($var)
    {
        GPBUtil::checkString($var, True);
        $this->express = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string code = 2;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>string code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 rate = 3;</code>
     * @return int
     */
    public function getRate()
    {
        return $this->rate;
    }

    /**
     * Generated from protobuf field <code>int32 rate = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setRate($var)
    {
        GPBUtil::checkInt32($var);
        $this->rate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 id = 4;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

}

