<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qpm.proto

namespace Yinge\Grpc\Qpm;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Qpm.FactoryExpressResponse</code>
 */
class FactoryExpressResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 count = 1;</code>
     */
    protected $count = 0;
    /**
     * Generated from protobuf field <code>repeated .Qpm.FactoryExpressItem expresses = 2;</code>
     */
    private $expresses;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $count
     *     @type \Yinge\Grpc\Qpm\FactoryExpressItem[]|\Google\Protobuf\Internal\RepeatedField $expresses
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Qpm\GPBMetadata\Qpm::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 count = 1;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * Generated from protobuf field <code>int32 count = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Qpm.FactoryExpressItem expresses = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getExpresses()
    {
        return $this->expresses;
    }

    /**
     * Generated from protobuf field <code>repeated .Qpm.FactoryExpressItem expresses = 2;</code>
     * @param \Yinge\Grpc\Qpm\FactoryExpressItem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setExpresses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Yinge\Grpc\Qpm\FactoryExpressItem::class);
        $this->expresses = $arr;

        return $this;
    }

}

