<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qpm.proto

namespace Yinge\Grpc\Qpm;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Qpm.OrderCostDetail</code>
 */
class OrderCostDetail extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 factoryId = 1;</code>
     */
    protected $factoryId = 0;
    /**
     * Generated from protobuf field <code>int32 productionOrderId = 2;</code>
     */
    protected $productionOrderId = 0;
    /**
     * Generated from protobuf field <code>int32 scmSkuId = 3;</code>
     */
    protected $scmSkuId = 0;
    /**
     * Generated from protobuf field <code>int32 expressBranchId = 4;</code>
     */
    protected $expressBranchId = 0;
    /**
     * Generated from protobuf field <code>string province = 5;</code>
     */
    protected $province = '';
    /**
     * Generated from protobuf field <code>int32 costSubType = 6;</code>
     */
    protected $costSubType = 0;
    /**
     * Generated from protobuf field <code>float cost = 7;</code>
     */
    protected $cost = 0.0;
    /**
     * Generated from protobuf field <code>int32 settledAt = 8;</code>
     */
    protected $settledAt = 0;
    /**
     * Generated from protobuf field <code>int32 hasPaid = 9;</code>
     */
    protected $hasPaid = 0;
    /**
     * Generated from protobuf field <code>int32 createdAt = 10;</code>
     */
    protected $createdAt = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $factoryId
     *     @type int $productionOrderId
     *     @type int $scmSkuId
     *     @type int $expressBranchId
     *     @type string $province
     *     @type int $costSubType
     *     @type float $cost
     *     @type int $settledAt
     *     @type int $hasPaid
     *     @type int $createdAt
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Qpm\GPBMetadata\Qpm::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 factoryId = 1;</code>
     * @return int
     */
    public function getFactoryId()
    {
        return $this->factoryId;
    }

    /**
     * Generated from protobuf field <code>int32 factoryId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setFactoryId($var)
    {
        GPBUtil::checkInt32($var);
        $this->factoryId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 productionOrderId = 2;</code>
     * @return int
     */
    public function getProductionOrderId()
    {
        return $this->productionOrderId;
    }

    /**
     * Generated from protobuf field <code>int32 productionOrderId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setProductionOrderId($var)
    {
        GPBUtil::checkInt32($var);
        $this->productionOrderId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 scmSkuId = 3;</code>
     * @return int
     */
    public function getScmSkuId()
    {
        return $this->scmSkuId;
    }

    /**
     * Generated from protobuf field <code>int32 scmSkuId = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setScmSkuId($var)
    {
        GPBUtil::checkInt32($var);
        $this->scmSkuId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 expressBranchId = 4;</code>
     * @return int
     */
    public function getExpressBranchId()
    {
        return $this->expressBranchId;
    }

    /**
     * Generated from protobuf field <code>int32 expressBranchId = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setExpressBranchId($var)
    {
        GPBUtil::checkInt32($var);
        $this->expressBranchId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string province = 5;</code>
     * @return string
     */
    public function getProvince()
    {
        return $this->province;
    }

    /**
     * Generated from protobuf field <code>string province = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setProvince($var)
    {
        GPBUtil::checkString($var, True);
        $this->province = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 costSubType = 6;</code>
     * @return int
     */
    public function getCostSubType()
    {
        return $this->costSubType;
    }

    /**
     * Generated from protobuf field <code>int32 costSubType = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setCostSubType($var)
    {
        GPBUtil::checkInt32($var);
        $this->costSubType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float cost = 7;</code>
     * @return float
     */
    public function getCost()
    {
        return $this->cost;
    }

    /**
     * Generated from protobuf field <code>float cost = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setCost($var)
    {
        GPBUtil::checkFloat($var);
        $this->cost = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 settledAt = 8;</code>
     * @return int
     */
    public function getSettledAt()
    {
        return $this->settledAt;
    }

    /**
     * Generated from protobuf field <code>int32 settledAt = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setSettledAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->settledAt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 hasPaid = 9;</code>
     * @return int
     */
    public function getHasPaid()
    {
        return $this->hasPaid;
    }

    /**
     * Generated from protobuf field <code>int32 hasPaid = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setHasPaid($var)
    {
        GPBUtil::checkInt32($var);
        $this->hasPaid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 createdAt = 10;</code>
     * @return int
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Generated from protobuf field <code>int32 createdAt = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->createdAt = $var;

        return $this;
    }

}

