<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qpm.proto

namespace Yinge\Grpc\Qpm;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Qpm.OrderCostDetailsResponse</code>
 */
class OrderCostDetailsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Qpm.OrderCostDetail costDetails = 1;</code>
     */
    private $costDetails;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Yinge\Grpc\Qpm\OrderCostDetail[]|\Google\Protobuf\Internal\RepeatedField $costDetails
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Qpm\GPBMetadata\Qpm::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Qpm.OrderCostDetail costDetails = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCostDetails()
    {
        return $this->costDetails;
    }

    /**
     * Generated from protobuf field <code>repeated .Qpm.OrderCostDetail costDetails = 1;</code>
     * @param \Yinge\Grpc\Qpm\OrderCostDetail[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCostDetails($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Yinge\Grpc\Qpm\OrderCostDetail::class);
        $this->costDetails = $arr;

        return $this;
    }

}

