<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qpm.proto

namespace Yinge\Grpc\Qpm;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Qpm.OrderCancelRequest</code>
 */
class OrderCancelRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 orderId = 1;</code>
     */
    protected $orderId = 0;
    /**
     * Generated from protobuf field <code>.Qpm.Operator operator = 3;</code>
     */
    protected $operator = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $orderId
     *     @type \Yinge\Grpc\Qpm\Operator $operator
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Qpm\GPBMetadata\Qpm::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 orderId = 1;</code>
     * @return int
     */
    public function getOrderId()
    {
        return $this->orderId;
    }

    /**
     * Generated from protobuf field <code>int32 orderId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setOrderId($var)
    {
        GPBUtil::checkInt32($var);
        $this->orderId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Qpm.Operator operator = 3;</code>
     * @return \Yinge\Grpc\Qpm\Operator
     */
    public function getOperator () {
        return isset($this->operator) ? $this->operator : null;
    }

    public function hasOperator () {
        return isset($this->operator);
    }

    public function clearOperator () {
        unset($this->operator);
    }

    /**
     * Generated from protobuf field <code>.Qpm.Operator operator = 3;</code>
     * @param \Yinge\Grpc\Qpm\Operator $var
     * @return $this
     */
    public function setOperator ($var) {
        GPBUtil::checkMessage($var, \Yinge\Grpc\Qpm\Operator::class);
        $this->operator = $var;

        return $this;
    }

}

