<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qpm.proto

namespace Yinge\Grpc\Qpm;

if (false) {
    /**
     * This class is deprecated. Use Yinge\Grpc\Qpm\ProduceCheckResponse\CheckItem instead.
     * @deprecated
     */
    class ProduceCheckResponse_CheckItem {}
}
class_exists(ProduceCheckResponse\CheckItem::class);
@trigger_error('Yinge\Grpc\Qpm\ProduceCheckResponse_CheckItem is deprecated and will be removed in the next major release. Use Yinge\Grpc\Qpm\ProduceCheckResponse\CheckItem instead', E_USER_DEPRECATED);

