<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qpm.proto

namespace Yinge\Grpc\Qpm;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Qpm.ScmOrder</code>
 */
class ScmOrder extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>int32 orderId = 2;</code>
     */
    protected $orderId = 0;
    /**
     * Generated from protobuf field <code>int32 packingId = 3;</code>
     */
    protected $packingId = 0;
    /**
     * Generated from protobuf field <code>int32 deliverId = 4;</code>
     */
    protected $deliverId = 0;
    /**
     * Generated from protobuf field <code>int32 factoryId = 5;</code>
     */
    protected $factoryId = 0;
    /**
     * Generated from protobuf field <code>int32 productionStatus = 6;</code>
     */
    protected $productionStatus = 0;
    /**
     * Generated from protobuf field <code>int32 orderStatus = 7;</code>
     */
    protected $orderStatus = 0;
    /**
     * Generated from protobuf field <code>string addressInfo = 8;</code>
     */
    protected $addressInfo = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type int $orderId
     *     @type int $packingId
     *     @type int $deliverId
     *     @type int $factoryId
     *     @type int $productionStatus
     *     @type int $orderStatus
     *     @type string $addressInfo
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Qpm\GPBMetadata\Qpm::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 orderId = 2;</code>
     * @return int
     */
    public function getOrderId()
    {
        return $this->orderId;
    }

    /**
     * Generated from protobuf field <code>int32 orderId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOrderId($var)
    {
        GPBUtil::checkInt32($var);
        $this->orderId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 packingId = 3;</code>
     * @return int
     */
    public function getPackingId()
    {
        return $this->packingId;
    }

    /**
     * Generated from protobuf field <code>int32 packingId = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPackingId($var)
    {
        GPBUtil::checkInt32($var);
        $this->packingId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 deliverId = 4;</code>
     * @return int
     */
    public function getDeliverId()
    {
        return $this->deliverId;
    }

    /**
     * Generated from protobuf field <code>int32 deliverId = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setDeliverId($var)
    {
        GPBUtil::checkInt32($var);
        $this->deliverId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 factoryId = 5;</code>
     * @return int
     */
    public function getFactoryId()
    {
        return $this->factoryId;
    }

    /**
     * Generated from protobuf field <code>int32 factoryId = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setFactoryId($var)
    {
        GPBUtil::checkInt32($var);
        $this->factoryId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 productionStatus = 6;</code>
     * @return int
     */
    public function getProductionStatus()
    {
        return $this->productionStatus;
    }

    /**
     * Generated from protobuf field <code>int32 productionStatus = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setProductionStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->productionStatus = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 orderStatus = 7;</code>
     * @return int
     */
    public function getOrderStatus()
    {
        return $this->orderStatus;
    }

    /**
     * Generated from protobuf field <code>int32 orderStatus = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setOrderStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->orderStatus = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string addressInfo = 8;</code>
     * @return string
     */
    public function getAddressInfo()
    {
        return $this->addressInfo;
    }

    /**
     * Generated from protobuf field <code>string addressInfo = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setAddressInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->addressInfo = $var;

        return $this;
    }

}

