<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qpm.proto

namespace Yinge\Grpc\Qpm;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Qpm.ShippingTrace</code>
 */
class ShippingTrace extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string mailNo = 1;</code>
     */
    protected $mailNo = '';
    /**
     * Generated from protobuf field <code>string logisticsGmtModified = 2;</code>
     */
    protected $logisticsGmtModified = '';
    /**
     * Generated from protobuf field <code>string lastLogisticDetail = 3;</code>
     */
    protected $lastLogisticDetail = '';
    /**
     * Generated from protobuf field <code>string logisticsStatus = 4;</code>
     */
    protected $logisticsStatus = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $mailNo
     *     @type string $logisticsGmtModified
     *     @type string $lastLogisticDetail
     *     @type string $logisticsStatus
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Qpm\GPBMetadata\Qpm::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string mailNo = 1;</code>
     * @return string
     */
    public function getMailNo()
    {
        return $this->mailNo;
    }

    /**
     * Generated from protobuf field <code>string mailNo = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMailNo($var)
    {
        GPBUtil::checkString($var, True);
        $this->mailNo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string logisticsGmtModified = 2;</code>
     * @return string
     */
    public function getLogisticsGmtModified()
    {
        return $this->logisticsGmtModified;
    }

    /**
     * Generated from protobuf field <code>string logisticsGmtModified = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLogisticsGmtModified($var)
    {
        GPBUtil::checkString($var, True);
        $this->logisticsGmtModified = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string lastLogisticDetail = 3;</code>
     * @return string
     */
    public function getLastLogisticDetail()
    {
        return $this->lastLogisticDetail;
    }

    /**
     * Generated from protobuf field <code>string lastLogisticDetail = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLastLogisticDetail($var)
    {
        GPBUtil::checkString($var, True);
        $this->lastLogisticDetail = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string logisticsStatus = 4;</code>
     * @return string
     */
    public function getLogisticsStatus()
    {
        return $this->logisticsStatus;
    }

    /**
     * Generated from protobuf field <code>string logisticsStatus = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setLogisticsStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->logisticsStatus = $var;

        return $this;
    }

}

