<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qpm.proto

namespace Yinge\Grpc\Qpm;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Qpm.SkuListReq</code>
 */
class SkuListReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 factoryId = 1;</code>
     */
    protected $factoryId = 0;
    /**
     * Generated from protobuf field <code>int64 spuId = 2;</code>
     */
    protected $spuId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $factoryId
     *     @type int|string $spuId
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Qpm\GPBMetadata\Qpm::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 factoryId = 1;</code>
     * @return int|string
     */
    public function getFactoryId()
    {
        return $this->factoryId;
    }

    /**
     * Generated from protobuf field <code>int64 factoryId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFactoryId($var)
    {
        GPBUtil::checkInt64($var);
        $this->factoryId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 spuId = 2;</code>
     * @return int|string
     */
    public function getSpuId()
    {
        return $this->spuId;
    }

    /**
     * Generated from protobuf field <code>int64 spuId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSpuId($var)
    {
        GPBUtil::checkInt64($var);
        $this->spuId = $var;

        return $this;
    }

}

