<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qpm.proto

namespace Yinge\Grpc\Qpm;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 入库详情 结果
 *
 * Generated from protobuf message <code>Qpm.SMDResp</code>
 */
class SMDResp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 mid = 1;</code>
     */
    protected $mid = 0;
    /**
     * Generated from protobuf field <code>int64 factoryId = 2;</code>
     */
    protected $factoryId = 0;
    /**
     * Generated from protobuf field <code>int64 storeNum = 3;</code>
     */
    protected $storeNum = 0;
    /**
     * Generated from protobuf field <code>int64 storeType = 4;</code>
     */
    protected $storeType = 0;
    /**
     * Generated from protobuf field <code>int64 stockType = 5;</code>
     */
    protected $stockType = 0;
    /**
     * Generated from protobuf field <code>int64 id = 6;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>int64 checkId = 7;</code>
     */
    protected $checkId = 0;
    /**
     * Generated from protobuf field <code>int64 beforeYingeStock = 8;</code>
     */
    protected $beforeYingeStock = 0;
    /**
     * Generated from protobuf field <code>int64 afterYingeStock = 9;</code>
     */
    protected $afterYingeStock = 0;
    /**
     * Generated from protobuf field <code>int64 beforeScmStock = 10;</code>
     */
    protected $beforeScmStock = 0;
    /**
     * Generated from protobuf field <code>int64 afterScmStock = 11;</code>
     */
    protected $afterScmStock = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $mid
     *     @type int|string $factoryId
     *     @type int|string $storeNum
     *     @type int|string $storeType
     *     @type int|string $stockType
     *     @type int|string $id
     *     @type int|string $checkId
     *     @type int|string $beforeYingeStock
     *     @type int|string $afterYingeStock
     *     @type int|string $beforeScmStock
     *     @type int|string $afterScmStock
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Qpm\GPBMetadata\Qpm::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 mid = 1;</code>
     * @return int|string
     */
    public function getMid()
    {
        return $this->mid;
    }

    /**
     * Generated from protobuf field <code>int64 mid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMid($var)
    {
        GPBUtil::checkInt64($var);
        $this->mid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 factoryId = 2;</code>
     * @return int|string
     */
    public function getFactoryId()
    {
        return $this->factoryId;
    }

    /**
     * Generated from protobuf field <code>int64 factoryId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFactoryId($var)
    {
        GPBUtil::checkInt64($var);
        $this->factoryId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 storeNum = 3;</code>
     * @return int|string
     */
    public function getStoreNum()
    {
        return $this->storeNum;
    }

    /**
     * Generated from protobuf field <code>int64 storeNum = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStoreNum($var)
    {
        GPBUtil::checkInt64($var);
        $this->storeNum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 storeType = 4;</code>
     * @return int|string
     */
    public function getStoreType()
    {
        return $this->storeType;
    }

    /**
     * Generated from protobuf field <code>int64 storeType = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStoreType($var)
    {
        GPBUtil::checkInt64($var);
        $this->storeType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 stockType = 5;</code>
     * @return int|string
     */
    public function getStockType()
    {
        return $this->stockType;
    }

    /**
     * Generated from protobuf field <code>int64 stockType = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStockType($var)
    {
        GPBUtil::checkInt64($var);
        $this->stockType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 id = 6;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 checkId = 7;</code>
     * @return int|string
     */
    public function getCheckId()
    {
        return $this->checkId;
    }

    /**
     * Generated from protobuf field <code>int64 checkId = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCheckId($var)
    {
        GPBUtil::checkInt64($var);
        $this->checkId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 beforeYingeStock = 8;</code>
     * @return int|string
     */
    public function getBeforeYingeStock()
    {
        return $this->beforeYingeStock;
    }

    /**
     * Generated from protobuf field <code>int64 beforeYingeStock = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBeforeYingeStock($var)
    {
        GPBUtil::checkInt64($var);
        $this->beforeYingeStock = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 afterYingeStock = 9;</code>
     * @return int|string
     */
    public function getAfterYingeStock()
    {
        return $this->afterYingeStock;
    }

    /**
     * Generated from protobuf field <code>int64 afterYingeStock = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAfterYingeStock($var)
    {
        GPBUtil::checkInt64($var);
        $this->afterYingeStock = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 beforeScmStock = 10;</code>
     * @return int|string
     */
    public function getBeforeScmStock()
    {
        return $this->beforeScmStock;
    }

    /**
     * Generated from protobuf field <code>int64 beforeScmStock = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBeforeScmStock($var)
    {
        GPBUtil::checkInt64($var);
        $this->beforeScmStock = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 afterScmStock = 11;</code>
     * @return int|string
     */
    public function getAfterScmStock()
    {
        return $this->afterScmStock;
    }

    /**
     * Generated from protobuf field <code>int64 afterScmStock = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAfterScmStock($var)
    {
        GPBUtil::checkInt64($var);
        $this->afterScmStock = $var;

        return $this;
    }

}

