<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qpm.proto

namespace Yinge\Grpc\Qpm;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 入库历史请求参数
 *
 * Generated from protobuf message <code>Qpm.SMHReq</code>
 */
class SMHReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 page = 1;</code>
     */
    protected $page = 0;
    /**
     * Generated from protobuf field <code>int64 pageSize = 2;</code>
     */
    protected $pageSize = 0;
    /**
     * Generated from protobuf field <code>int64 spuId = 3;</code>
     */
    protected $spuId = 0;
    /**
     * Generated from protobuf field <code>string startAt = 4;</code>
     */
    protected $startAt = '';
    /**
     * Generated from protobuf field <code>string endAt = 5;</code>
     */
    protected $endAt = '';
    /**
     * Generated from protobuf field <code>int64 factoryId = 6;</code>
     */
    protected $factoryId = 0;
    /**
     * Generated from protobuf field <code>int64 mid = 7;</code>
     */
    protected $mid = 0;
    /**
     * Generated from protobuf field <code>int64 status = 8;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>int64 relationCheckId = 9;</code>
     */
    protected $relationCheckId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $page
     *     @type int|string $pageSize
     *     @type int|string $spuId
     *     @type string $startAt
     *     @type string $endAt
     *     @type int|string $factoryId
     *     @type int|string $mid
     *     @type int|string $status
     *     @type int|string $relationCheckId
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Qpm\GPBMetadata\Qpm::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 page = 1;</code>
     * @return int|string
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * Generated from protobuf field <code>int64 page = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt64($var);
        $this->page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 pageSize = 2;</code>
     * @return int|string
     */
    public function getPageSize()
    {
        return $this->pageSize;
    }

    /**
     * Generated from protobuf field <code>int64 pageSize = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->pageSize = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 spuId = 3;</code>
     * @return int|string
     */
    public function getSpuId()
    {
        return $this->spuId;
    }

    /**
     * Generated from protobuf field <code>int64 spuId = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSpuId($var)
    {
        GPBUtil::checkInt64($var);
        $this->spuId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string startAt = 4;</code>
     * @return string
     */
    public function getStartAt()
    {
        return $this->startAt;
    }

    /**
     * Generated from protobuf field <code>string startAt = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setStartAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->startAt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string endAt = 5;</code>
     * @return string
     */
    public function getEndAt()
    {
        return $this->endAt;
    }

    /**
     * Generated from protobuf field <code>string endAt = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setEndAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->endAt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 factoryId = 6;</code>
     * @return int|string
     */
    public function getFactoryId()
    {
        return $this->factoryId;
    }

    /**
     * Generated from protobuf field <code>int64 factoryId = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFactoryId($var)
    {
        GPBUtil::checkInt64($var);
        $this->factoryId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 mid = 7;</code>
     * @return int|string
     */
    public function getMid()
    {
        return $this->mid;
    }

    /**
     * Generated from protobuf field <code>int64 mid = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMid($var)
    {
        GPBUtil::checkInt64($var);
        $this->mid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 status = 8;</code>
     * @return int|string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>int64 status = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt64($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 relationCheckId = 9;</code>
     * @return int|string
     */
    public function getRelationCheckId()
    {
        return $this->relationCheckId;
    }

    /**
     * Generated from protobuf field <code>int64 relationCheckId = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRelationCheckId($var)
    {
        GPBUtil::checkInt64($var);
        $this->relationCheckId = $var;

        return $this;
    }

}

