<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qpm.proto

namespace Yinge\Grpc\Qpm;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Qpm.SortingBatch</code>
 */
class SortingBatch extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 batchId = 1;</code>
     */
    protected $batchId = 0;
    /**
     * Generated from protobuf field <code>string batchNo = 2;</code>
     */
    protected $batchNo = '';
    /**
     * Generated from protobuf field <code>int32 produceFactoryId = 3;</code>
     */
    protected $produceFactoryId = 0;
    /**
     * Generated from protobuf field <code>int32 sortingFactoryId = 4;</code>
     */
    protected $sortingFactoryId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $batchId
     *     @type string $batchNo
     *     @type int $produceFactoryId
     *     @type int $sortingFactoryId
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Qpm\GPBMetadata\Qpm::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 batchId = 1;</code>
     * @return int
     */
    public function getBatchId()
    {
        return $this->batchId;
    }

    /**
     * Generated from protobuf field <code>int32 batchId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setBatchId($var)
    {
        GPBUtil::checkInt32($var);
        $this->batchId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string batchNo = 2;</code>
     * @return string
     */
    public function getBatchNo()
    {
        return $this->batchNo;
    }

    /**
     * Generated from protobuf field <code>string batchNo = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBatchNo($var)
    {
        GPBUtil::checkString($var, True);
        $this->batchNo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 produceFactoryId = 3;</code>
     * @return int
     */
    public function getProduceFactoryId()
    {
        return $this->produceFactoryId;
    }

    /**
     * Generated from protobuf field <code>int32 produceFactoryId = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setProduceFactoryId($var)
    {
        GPBUtil::checkInt32($var);
        $this->produceFactoryId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 sortingFactoryId = 4;</code>
     * @return int
     */
    public function getSortingFactoryId()
    {
        return $this->sortingFactoryId;
    }

    /**
     * Generated from protobuf field <code>int32 sortingFactoryId = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setSortingFactoryId($var)
    {
        GPBUtil::checkInt32($var);
        $this->sortingFactoryId = $var;

        return $this;
    }

}

