<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qpm.proto

namespace Yinge\Grpc\Qpm;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 入库物料请求参数
 *
 * Generated from protobuf message <code>Qpm.StoreMaterielReq</code>
 */
class StoreMaterielReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated int64 mids = 1;</code>
     */
    private $mids;
    /**
     * Generated from protobuf field <code>int64 storeNum = 2;</code>
     */
    protected $storeNum = 0;
    /**
     * Generated from protobuf field <code>int32 storeType = 3;</code>
     */
    protected $storeType = 0;
    /**
     * Generated from protobuf field <code>string cert = 4;</code>
     */
    protected $cert = '';
    /**
     * Generated from protobuf field <code>int64 factoryId = 5;</code>
     */
    protected $factoryId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $mids
     *     @type int|string $storeNum
     *     @type int $storeType
     *     @type string $cert
     *     @type int|string $factoryId
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Qpm\GPBMetadata\Qpm::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated int64 mids = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMids()
    {
        return $this->mids;
    }

    /**
     * Generated from protobuf field <code>repeated int64 mids = 1;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMids($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->mids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 storeNum = 2;</code>
     * @return int|string
     */
    public function getStoreNum()
    {
        return $this->storeNum;
    }

    /**
     * Generated from protobuf field <code>int64 storeNum = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStoreNum($var)
    {
        GPBUtil::checkInt64($var);
        $this->storeNum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 storeType = 3;</code>
     * @return int
     */
    public function getStoreType()
    {
        return $this->storeType;
    }

    /**
     * Generated from protobuf field <code>int32 storeType = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setStoreType($var)
    {
        GPBUtil::checkInt32($var);
        $this->storeType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cert = 4;</code>
     * @return string
     */
    public function getCert()
    {
        return $this->cert;
    }

    /**
     * Generated from protobuf field <code>string cert = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCert($var)
    {
        GPBUtil::checkString($var, True);
        $this->cert = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 factoryId = 5;</code>
     * @return int|string
     */
    public function getFactoryId()
    {
        return $this->factoryId;
    }

    /**
     * Generated from protobuf field <code>int64 factoryId = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFactoryId($var)
    {
        GPBUtil::checkInt64($var);
        $this->factoryId = $var;

        return $this;
    }

}

