<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qpm.proto

namespace Yinge\Grpc\Qpm;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 用于不同方法
 *
 * Generated from protobuf message <code>Qpm.SubAccountAuthRequest</code>
 */
class SubAccountAuthRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 factoryId = 1;</code>
     */
    protected $factoryId = 0;
    /**
     * Generated from protobuf field <code>int32 roleId = 2;</code>
     */
    protected $roleId = 0;
    /**
     * Generated from protobuf field <code>string name = 3;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>int32 subAccountId = 4;</code>
     */
    protected $subAccountId = 0;
    /**
     * Generated from protobuf field <code>repeated int32 authIds = 5;</code>
     */
    private $authIds;
    /**
     * Generated from protobuf field <code>string funcName = 6;</code>
     */
    protected $funcName = '';
    /**
     * Generated from protobuf field <code>string phone = 7;</code>
     */
    protected $phone = '';
    /**
     * Generated from protobuf field <code>string captcha = 8;</code>
     */
    protected $captcha = '';
    /**
     * Generated from protobuf field <code>int32 page = 9;</code>
     */
    protected $page = 0;
    /**
     * Generated from protobuf field <code>int32 pageSize = 10;</code>
     */
    protected $pageSize = 0;
    /**
     * Generated from protobuf field <code>string nickname = 11;</code>
     */
    protected $nickname = '';
    /**
     * Generated from protobuf field <code>bool listView = 12;</code>
     */
    protected $listView = false;
    /**
     * Generated from protobuf field <code>string channel = 13;</code>
     */
    protected $channel = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $factoryId
     *     @type int $roleId
     *     @type string $name
     *     @type int $subAccountId
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $authIds
     *     @type string $funcName
     *     @type string $phone
     *     @type string $captcha
     *     @type int $page
     *     @type int $pageSize
     *     @type string $nickname
     *     @type bool $listView
     *     @type string $channel
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Qpm\GPBMetadata\Qpm::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 factoryId = 1;</code>
     * @return int
     */
    public function getFactoryId()
    {
        return $this->factoryId;
    }

    /**
     * Generated from protobuf field <code>int32 factoryId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setFactoryId($var)
    {
        GPBUtil::checkInt32($var);
        $this->factoryId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 roleId = 2;</code>
     * @return int
     */
    public function getRoleId()
    {
        return $this->roleId;
    }

    /**
     * Generated from protobuf field <code>int32 roleId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setRoleId($var)
    {
        GPBUtil::checkInt32($var);
        $this->roleId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 subAccountId = 4;</code>
     * @return int
     */
    public function getSubAccountId()
    {
        return $this->subAccountId;
    }

    /**
     * Generated from protobuf field <code>int32 subAccountId = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setSubAccountId($var)
    {
        GPBUtil::checkInt32($var);
        $this->subAccountId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 authIds = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAuthIds()
    {
        return $this->authIds;
    }

    /**
     * Generated from protobuf field <code>repeated int32 authIds = 5;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAuthIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->authIds = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string funcName = 6;</code>
     * @return string
     */
    public function getFuncName()
    {
        return $this->funcName;
    }

    /**
     * Generated from protobuf field <code>string funcName = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setFuncName($var)
    {
        GPBUtil::checkString($var, True);
        $this->funcName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string phone = 7;</code>
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * Generated from protobuf field <code>string phone = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string captcha = 8;</code>
     * @return string
     */
    public function getCaptcha()
    {
        return $this->captcha;
    }

    /**
     * Generated from protobuf field <code>string captcha = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setCaptcha($var)
    {
        GPBUtil::checkString($var, True);
        $this->captcha = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 page = 9;</code>
     * @return int
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * Generated from protobuf field <code>int32 page = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 pageSize = 10;</code>
     * @return int
     */
    public function getPageSize()
    {
        return $this->pageSize;
    }

    /**
     * Generated from protobuf field <code>int32 pageSize = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->pageSize = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string nickname = 11;</code>
     * @return string
     */
    public function getNickname()
    {
        return $this->nickname;
    }

    /**
     * Generated from protobuf field <code>string nickname = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setNickname($var)
    {
        GPBUtil::checkString($var, True);
        $this->nickname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool listView = 12;</code>
     * @return bool
     */
    public function getListView()
    {
        return $this->listView;
    }

    /**
     * Generated from protobuf field <code>bool listView = 12;</code>
     * @param bool $var
     * @return $this
     */
    public function setListView($var)
    {
        GPBUtil::checkBool($var);
        $this->listView = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string channel = 13;</code>
     * @return string
     */
    public function getChannel()
    {
        return $this->channel;
    }

    /**
     * Generated from protobuf field <code>string channel = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setChannel($var)
    {
        GPBUtil::checkString($var, True);
        $this->channel = $var;

        return $this;
    }

}

