<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qpm.proto

namespace Yinge\Grpc\Qpm;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Qpm.SupportFactoryRequest</code>
 */
class SupportFactoryRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>bool onlyProduceEnabled = 2;</code>
     */
    protected $onlyProduceEnabled = false;
    /**
     * Generated from protobuf field <code>bool onlyAutoDispatchEnabled = 3;</code>
     */
    protected $onlyAutoDispatchEnabled = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type bool $onlyProduceEnabled
     *     @type bool $onlyAutoDispatchEnabled
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Qpm\GPBMetadata\Qpm::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool onlyProduceEnabled = 2;</code>
     * @return bool
     */
    public function getOnlyProduceEnabled()
    {
        return $this->onlyProduceEnabled;
    }

    /**
     * Generated from protobuf field <code>bool onlyProduceEnabled = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setOnlyProduceEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->onlyProduceEnabled = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool onlyAutoDispatchEnabled = 3;</code>
     * @return bool
     */
    public function getOnlyAutoDispatchEnabled()
    {
        return $this->onlyAutoDispatchEnabled;
    }

    /**
     * Generated from protobuf field <code>bool onlyAutoDispatchEnabled = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setOnlyAutoDispatchEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->onlyAutoDispatchEnabled = $var;

        return $this;
    }

}

