<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qpm.proto

namespace Yinge\Grpc\Qpm;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Qpm.SyncStatusRequest</code>
 */
class SyncStatusRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 orderId = 1;</code>
     */
    protected $orderId = 0;
    /**
     * Generated from protobuf field <code>int32 orderStatus = 2;</code>
     */
    protected $orderStatus = 0;
    /**
     * Generated from protobuf field <code>int32 produceStatus = 3;</code>
     */
    protected $produceStatus = 0;
    /**
     * Generated from protobuf field <code>int32 shippingStatus = 4;</code>
     */
    protected $shippingStatus = 0;
    /**
     * Generated from protobuf field <code>int32 deliveryStatus = 5;</code>
     */
    protected $deliveryStatus = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $orderId
     *     @type int $orderStatus
     *     @type int $produceStatus
     *     @type int $shippingStatus
     *     @type int $deliveryStatus
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Qpm\GPBMetadata\Qpm::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 orderId = 1;</code>
     * @return int
     */
    public function getOrderId()
    {
        return $this->orderId;
    }

    /**
     * Generated from protobuf field <code>int32 orderId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setOrderId($var)
    {
        GPBUtil::checkInt32($var);
        $this->orderId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 orderStatus = 2;</code>
     * @return int
     */
    public function getOrderStatus()
    {
        return $this->orderStatus;
    }

    /**
     * Generated from protobuf field <code>int32 orderStatus = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOrderStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->orderStatus = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 produceStatus = 3;</code>
     * @return int
     */
    public function getProduceStatus()
    {
        return $this->produceStatus;
    }

    /**
     * Generated from protobuf field <code>int32 produceStatus = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setProduceStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->produceStatus = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 shippingStatus = 4;</code>
     * @return int
     */
    public function getShippingStatus()
    {
        return $this->shippingStatus;
    }

    /**
     * Generated from protobuf field <code>int32 shippingStatus = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setShippingStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->shippingStatus = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 deliveryStatus = 5;</code>
     * @return int
     */
    public function getDeliveryStatus()
    {
        return $this->deliveryStatus;
    }

    /**
     * Generated from protobuf field <code>int32 deliveryStatus = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setDeliveryStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->deliveryStatus = $var;

        return $this;
    }

}

