<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qpm.proto

namespace Yinge\Grpc\Qpm;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Qpm.WmsDeliverProductsResp</code>
 */
class WmsDeliverProductsResp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Qpm.WmsDeliverConfig configs = 1;</code>
     */
    private $configs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Yinge\Grpc\Qpm\WmsDeliverConfig[]|\Google\Protobuf\Internal\RepeatedField $configs
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Qpm\GPBMetadata\Qpm::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Qpm.WmsDeliverConfig configs = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getConfigs()
    {
        return $this->configs;
    }

    /**
     * Generated from protobuf field <code>repeated .Qpm.WmsDeliverConfig configs = 1;</code>
     * @param \Yinge\Grpc\Qpm\WmsDeliverConfig[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setConfigs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Yinge\Grpc\Qpm\WmsDeliverConfig::class);
        $this->configs = $arr;

        return $this;
    }

}

