<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Yinge\Grpc\Finance\BindBankRequest;

use UnexpectedValueException;

/**
 * Protobuf type <code>finance.BindBankRequest.AccountType</code>
 */
class AccountType
{
    /**
     * Generated from protobuf enum <code>Person = 0;</code>
     */
    const Person = 0;
    /**
     * Generated from protobuf enum <code>Individual = 1;</code>
     */
    const Individual = 1;
    /**
     * Generated from protobuf enum <code>Enterprise = 2;</code>
     */
    const Enterprise = 2;

    private static $valueToName = [
        self::Person => 'Person',
        self::Individual => 'Individual',
        self::Enterprise => 'Enterprise',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(AccountType::class, \Yinge\Grpc\Finance\BindBankRequest_AccountType::class);

