<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: invoice.proto

namespace Yinge\Grpc\Invoice;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *开票明细
 *
 * Generated from protobuf message <code>Invoice.InvoiceApplyDetail</code>
 */
class InvoiceApplyDetail extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string bizProdName = 1;</code>
     */
    protected $bizProdName = '';
    /**
     * Generated from protobuf field <code>int32 count = 2;</code>
     */
    protected $count = 0;
    /**
     * Generated from protobuf field <code>float price = 3;</code>
     */
    protected $price = 0.0;
    /**
     * Generated from protobuf field <code>int32 skuId = 4;</code>
     */
    protected $skuId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $bizProdName
     *     @type int $count
     *     @type float $price
     *     @type int $skuId
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Invoice\GPBMetadata\Invoice::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string bizProdName = 1;</code>
     * @return string
     */
    public function getBizProdName()
    {
        return $this->bizProdName;
    }

    /**
     * Generated from protobuf field <code>string bizProdName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBizProdName($var)
    {
        GPBUtil::checkString($var, True);
        $this->bizProdName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 count = 2;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * Generated from protobuf field <code>int32 count = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float price = 3;</code>
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>float price = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkFloat($var);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 skuId = 4;</code>
     * @return int
     */
    public function getSkuId()
    {
        return $this->skuId;
    }

    /**
     * Generated from protobuf field <code>int32 skuId = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setSkuId($var)
    {
        GPBUtil::checkInt32($var);
        $this->skuId = $var;

        return $this;
    }

}

