<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: invoice.proto

namespace Yinge\Grpc\Invoice;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *专票信息
 *
 * Generated from protobuf message <code>Invoice.SpecialInfo</code>
 */
class SpecialInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string bankName = 1;</code>
     */
    protected $bankName = '';
    /**
     * Generated from protobuf field <code>string bankCardNum = 2;</code>
     */
    protected $bankCardNum = '';
    /**
     * Generated from protobuf field <code>string registerAddress = 3;</code>
     */
    protected $registerAddress = '';
    /**
     * Generated from protobuf field <code>string registerPhone = 4;</code>
     */
    protected $registerPhone = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $bankName
     *     @type string $bankCardNum
     *     @type string $registerAddress
     *     @type string $registerPhone
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Invoice\GPBMetadata\Invoice::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string bankName = 1;</code>
     * @return string
     */
    public function getBankName()
    {
        return $this->bankName;
    }

    /**
     * Generated from protobuf field <code>string bankName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBankName($var)
    {
        GPBUtil::checkString($var, True);
        $this->bankName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bankCardNum = 2;</code>
     * @return string
     */
    public function getBankCardNum()
    {
        return $this->bankCardNum;
    }

    /**
     * Generated from protobuf field <code>string bankCardNum = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBankCardNum($var)
    {
        GPBUtil::checkString($var, True);
        $this->bankCardNum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string registerAddress = 3;</code>
     * @return string
     */
    public function getRegisterAddress()
    {
        return $this->registerAddress;
    }

    /**
     * Generated from protobuf field <code>string registerAddress = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRegisterAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->registerAddress = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string registerPhone = 4;</code>
     * @return string
     */
    public function getRegisterPhone()
    {
        return $this->registerPhone;
    }

    /**
     * Generated from protobuf field <code>string registerPhone = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setRegisterPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->registerPhone = $var;

        return $this;
    }

}

