<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qpm.proto

namespace Yinge\Grpc\Qpm\ProduceCheckResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Qpm.ProduceCheckResponse.CheckItem</code>
 */
class CheckItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 skuId = 1;</code>
     */
    protected $skuId = 0;
    /**
     * Generated from protobuf field <code>string skuName = 2;</code>
     */
    protected $skuName = '';
    /**
     * Generated from protobuf field <code>bool factory = 3;</code>
     */
    protected $factory = false;
    /**
     * Generated from protobuf field <code>bool express = 4;</code>
     */
    protected $express = false;
    /**
     * Generated from protobuf field <code>bool produceCost = 5;</code>
     */
    protected $produceCost = false;
    /**
     * Generated from protobuf field <code>bool expressCost = 6;</code>
     */
    protected $expressCost = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $skuId
     *     @type string $skuName
     *     @type bool $factory
     *     @type bool $express
     *     @type bool $produceCost
     *     @type bool $expressCost
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Qpm\GPBMetadata\Qpm::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 skuId = 1;</code>
     * @return int|string
     */
    public function getSkuId()
    {
        return $this->skuId;
    }

    /**
     * Generated from protobuf field <code>int64 skuId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSkuId($var)
    {
        GPBUtil::checkInt64($var);
        $this->skuId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string skuName = 2;</code>
     * @return string
     */
    public function getSkuName()
    {
        return $this->skuName;
    }

    /**
     * Generated from protobuf field <code>string skuName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSkuName($var)
    {
        GPBUtil::checkString($var, True);
        $this->skuName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool factory = 3;</code>
     * @return bool
     */
    public function getFactory()
    {
        return $this->factory;
    }

    /**
     * Generated from protobuf field <code>bool factory = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setFactory($var)
    {
        GPBUtil::checkBool($var);
        $this->factory = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool express = 4;</code>
     * @return bool
     */
    public function getExpress()
    {
        return $this->express;
    }

    /**
     * Generated from protobuf field <code>bool express = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setExpress($var)
    {
        GPBUtil::checkBool($var);
        $this->express = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool produceCost = 5;</code>
     * @return bool
     */
    public function getProduceCost()
    {
        return $this->produceCost;
    }

    /**
     * Generated from protobuf field <code>bool produceCost = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setProduceCost($var)
    {
        GPBUtil::checkBool($var);
        $this->produceCost = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool expressCost = 6;</code>
     * @return bool
     */
    public function getExpressCost()
    {
        return $this->expressCost;
    }

    /**
     * Generated from protobuf field <code>bool expressCost = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setExpressCost($var)
    {
        GPBUtil::checkBool($var);
        $this->expressCost = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(CheckItem::class, \Yinge\Grpc\Qpm\ProduceCheckResponse_CheckItem::class);

