<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vision.proto

namespace Yinge\Grpc\Vision;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Vision.RCBatchResponse</code>
 */
class RCBatchResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Vision.ImageInfo imageList = 1;</code>
     */
    private $imageList;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Yinge\Grpc\Vision\ImageInfo[]|\Google\Protobuf\Internal\RepeatedField $imageList
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Vision\GPBMetadata\Vision::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Vision.ImageInfo imageList = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getImageList()
    {
        return $this->imageList;
    }

    /**
     * Generated from protobuf field <code>repeated .Vision.ImageInfo imageList = 1;</code>
     * @param \Yinge\Grpc\Vision\ImageInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setImageList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Yinge\Grpc\Vision\ImageInfo::class);
        $this->imageList = $arr;

        return $this;
    }

}

