<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vision.proto

namespace Yinge\Grpc\Vision;

if (false) {
    /**
     * This class is deprecated. Use Yinge\Grpc\Vision\RCBatchRequest\Block instead.
     * @deprecated
     */
    class RCBatchRequest_Block {}
}
class_exists(RCBatchRequest\Block::class);
@trigger_error('Yinge\Grpc\Vision\RCBatchRequest_Block is deprecated and will be removed in the next major release. Use Yinge\Grpc\Vision\RCBatchRequest\Block instead', E_USER_DEPRECATED);

