<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vision.proto

namespace Yinge\Grpc\Vision;

if (false) {
    /**
     * This class is deprecated. Use Yinge\Grpc\Vision\RCMeshDirectionResponse\TestImage instead.
     * @deprecated
     */
    class RCMeshDirectionResponse_TestImage {}
}
class_exists(RCMeshDirectionResponse\TestImage::class);
@trigger_error('Yinge\Grpc\Vision\RCMeshDirectionResponse_TestImage is deprecated and will be removed in the next major release. Use Yinge\Grpc\Vision\RCMeshDirectionResponse\TestImage instead', E_USER_DEPRECATED);

