<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vision.proto

namespace Yinge\Grpc\Vision;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Vision.RCMeshDirectionRequest</code>
 */
class RCMeshDirectionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string maskUrl = 1;</code>
     */
    protected $maskUrl = '';
    /**
     * Generated from protobuf field <code>string testImgUrl = 2;</code>
     */
    protected $testImgUrl = '';
    /**
     * Generated from protobuf field <code>int32 direction = 3;</code>
     */
    protected $direction = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $maskUrl
     *     @type string $testImgUrl
     *     @type int $direction
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Vision\GPBMetadata\Vision::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string maskUrl = 1;</code>
     * @return string
     */
    public function getMaskUrl()
    {
        return $this->maskUrl;
    }

    /**
     * Generated from protobuf field <code>string maskUrl = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMaskUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->maskUrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string testImgUrl = 2;</code>
     * @return string
     */
    public function getTestImgUrl()
    {
        return $this->testImgUrl;
    }

    /**
     * Generated from protobuf field <code>string testImgUrl = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTestImgUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->testImgUrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 direction = 3;</code>
     * @return int
     */
    public function getDirection()
    {
        return $this->direction;
    }

    /**
     * Generated from protobuf field <code>int32 direction = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setDirection($var)
    {
        GPBUtil::checkInt32($var);
        $this->direction = $var;

        return $this;
    }

}

