<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vision.proto

namespace Yinge\Grpc\Vision;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 渲染中心模板配置
 *
 * Generated from protobuf message <code>Vision.TPLData</code>
 */
class TPLData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Vision.TPLData.Scene scene = 1;</code>
     */
    protected $scene = null;
    /**
     * Generated from protobuf field <code>repeated .Vision.TPLData.Mask maskList = 2;</code>
     */
    private $maskList;
    /**
     * Generated from protobuf field <code>repeated .Vision.TPLData.Shadow shadowList = 3;</code>
     */
    private $shadowList;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Yinge\Grpc\Vision\TPLData\Scene $scene
     *     @type \Yinge\Grpc\Vision\TPLData\Mask[]|\Google\Protobuf\Internal\RepeatedField $maskList
     *     @type \Yinge\Grpc\Vision\TPLData\Shadow[]|\Google\Protobuf\Internal\RepeatedField $shadowList
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Vision\GPBMetadata\Vision::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Vision.TPLData.Scene scene = 1;</code>
     * @return \Yinge\Grpc\Vision\TPLData\Scene
     */
    public function getScene()
    {
        return $this->scene;
    }

    /**
     * Generated from protobuf field <code>.Vision.TPLData.Scene scene = 1;</code>
     * @param \Yinge\Grpc\Vision\TPLData\Scene $var
     * @return $this
     */
    public function setScene($var)
    {
        GPBUtil::checkMessage($var, \Yinge\Grpc\Vision\TPLData_Scene::class);
        $this->scene = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Vision.TPLData.Mask maskList = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMaskList()
    {
        return $this->maskList;
    }

    /**
     * Generated from protobuf field <code>repeated .Vision.TPLData.Mask maskList = 2;</code>
     * @param \Yinge\Grpc\Vision\TPLData\Mask[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMaskList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Yinge\Grpc\Vision\TPLData\Mask::class);
        $this->maskList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Vision.TPLData.Shadow shadowList = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getShadowList()
    {
        return $this->shadowList;
    }

    /**
     * Generated from protobuf field <code>repeated .Vision.TPLData.Shadow shadowList = 3;</code>
     * @param \Yinge\Grpc\Vision\TPLData\Shadow[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setShadowList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Yinge\Grpc\Vision\TPLData\Shadow::class);
        $this->shadowList = $arr;

        return $this;
    }

}

