<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vision.proto

namespace Yinge\Grpc\Vision;

if (false) {
    /**
     * This class is deprecated. Use Yinge\Grpc\Vision\TPLData\Shadow instead.
     * @deprecated
     */
    class TPLData_Shadow {}
}
class_exists(TPLData\Shadow::class);
@trigger_error('Yinge\Grpc\Vision\TPLData_Shadow is deprecated and will be removed in the next major release. Use Yinge\Grpc\Vision\TPLData\Shadow instead', E_USER_DEPRECATED);

