<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vision.proto

namespace Yinge\Grpc\Vision;

if (false) {
    /**
     * This class is deprecated. Use Yinge\Grpc\Vision\TPLData\Scene instead.
     * @deprecated
     */
    class TPLData_Scene {}
}
class_exists(TPLData\Scene::class);
@trigger_error('Yinge\Grpc\Vision\TPLData_Scene is deprecated and will be removed in the next major release. Use Yinge\Grpc\Vision\TPLData\Scene instead', E_USER_DEPRECATED);

