<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Yinge\Grpc\Finance;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finance.AccountBalance</code>
 */
class AccountBalance extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 unsettledAmount = 1;</code>
     */
    protected $unsettledAmount = 0;
    /**
     * Generated from protobuf field <code>int64 withdrawable = 2;</code>
     */
    protected $withdrawable = 0;
    /**
     * Generated from protobuf field <code>int64 realTotalAmount = 3;</code>
     */
    protected $realTotalAmount = 0;
    /**
     * Generated from protobuf field <code>int64 realWithdrawable = 4;</code>
     */
    protected $realWithdrawable = 0;
    /**
     * Generated from protobuf field <code>int64 realFrozen = 5;</code>
     */
    protected $realFrozen = 0;
    /**
     * Generated from protobuf field <code>int64 checking = 6;</code>
     */
    protected $checking = 0;
    /**
     * Generated from protobuf field <code>int64 sysFrozen = 7;</code>
     */
    protected $sysFrozen = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $unsettledAmount
     *     @type int|string $withdrawable
     *     @type int|string $realTotalAmount
     *     @type int|string $realWithdrawable
     *     @type int|string $realFrozen
     *     @type int|string $checking
     *     @type int|string $sysFrozen
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Finance\GPBMetadata\Finance::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 unsettledAmount = 1;</code>
     * @return int|string
     */
    public function getUnsettledAmount()
    {
        return $this->unsettledAmount;
    }

    /**
     * Generated from protobuf field <code>int64 unsettledAmount = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUnsettledAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->unsettledAmount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 withdrawable = 2;</code>
     * @return int|string
     */
    public function getWithdrawable()
    {
        return $this->withdrawable;
    }

    /**
     * Generated from protobuf field <code>int64 withdrawable = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setWithdrawable($var)
    {
        GPBUtil::checkInt64($var);
        $this->withdrawable = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 realTotalAmount = 3;</code>
     * @return int|string
     */
    public function getRealTotalAmount()
    {
        return $this->realTotalAmount;
    }

    /**
     * Generated from protobuf field <code>int64 realTotalAmount = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRealTotalAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->realTotalAmount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 realWithdrawable = 4;</code>
     * @return int|string
     */
    public function getRealWithdrawable()
    {
        return $this->realWithdrawable;
    }

    /**
     * Generated from protobuf field <code>int64 realWithdrawable = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRealWithdrawable($var)
    {
        GPBUtil::checkInt64($var);
        $this->realWithdrawable = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 realFrozen = 5;</code>
     * @return int|string
     */
    public function getRealFrozen()
    {
        return $this->realFrozen;
    }

    /**
     * Generated from protobuf field <code>int64 realFrozen = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRealFrozen($var)
    {
        GPBUtil::checkInt64($var);
        $this->realFrozen = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 checking = 6;</code>
     * @return int|string
     */
    public function getChecking()
    {
        return $this->checking;
    }

    /**
     * Generated from protobuf field <code>int64 checking = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setChecking($var)
    {
        GPBUtil::checkInt64($var);
        $this->checking = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 sysFrozen = 7;</code>
     * @return int|string
     */
    public function getSysFrozen()
    {
        return $this->sysFrozen;
    }

    /**
     * Generated from protobuf field <code>int64 sysFrozen = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSysFrozen($var)
    {
        GPBUtil::checkInt64($var);
        $this->sysFrozen = $var;

        return $this;
    }

}

