<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Yinge\Grpc\Finance;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finance.AdditionalInfo</code>
 */
class AdditionalInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 type = 1;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string globalId = 3;</code>
     */
    protected $globalId = '';
    /**
     * Generated from protobuf field <code>string legalName = 4;</code>
     */
    protected $legalName = '';
    /**
     * Generated from protobuf field <code>string legalId = 5;</code>
     */
    protected $legalId = '';
    /**
     * Generated from protobuf field <code>string clientIp = 6;</code>
     */
    protected $clientIp = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $type
     *     @type string $name
     *     @type string $globalId
     *     @type string $legalName
     *     @type string $legalId
     *     @type string $clientIp
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Finance\GPBMetadata\Finance::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 type = 1;</code>
     * @return int|string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>int64 type = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt64($var);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string globalId = 3;</code>
     * @return string
     */
    public function getGlobalId()
    {
        return $this->globalId;
    }

    /**
     * Generated from protobuf field <code>string globalId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setGlobalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->globalId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string legalName = 4;</code>
     * @return string
     */
    public function getLegalName()
    {
        return $this->legalName;
    }

    /**
     * Generated from protobuf field <code>string legalName = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setLegalName($var)
    {
        GPBUtil::checkString($var, True);
        $this->legalName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string legalId = 5;</code>
     * @return string
     */
    public function getLegalId()
    {
        return $this->legalId;
    }

    /**
     * Generated from protobuf field <code>string legalId = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setLegalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->legalId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string clientIp = 6;</code>
     * @return string
     */
    public function getClientIp()
    {
        return $this->clientIp;
    }

    /**
     * Generated from protobuf field <code>string clientIp = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setClientIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientIp = $var;

        return $this;
    }

}

