<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Yinge\Grpc\Finance;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finance.AgreementRequest</code>
 */
class AgreementRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.finance.SingleMerchantQuery merchantInfo = 1;</code>
     */
    protected $merchantInfo = null;
    /**
     * Generated from protobuf field <code>string clientIp = 2;</code>
     */
    protected $clientIp = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Yinge\Grpc\Finance\SingleMerchantQuery $merchantInfo
     *     @type string $clientIp
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Finance\GPBMetadata\Finance::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.finance.SingleMerchantQuery merchantInfo = 1;</code>
     * @return \Yinge\Grpc\Finance\SingleMerchantQuery|null
     */
    public function getMerchantInfo()
    {
        return isset($this->merchantInfo) ? $this->merchantInfo : null;
    }

    public function hasMerchantInfo()
    {
        return isset($this->merchantInfo);
    }

    public function clearMerchantInfo()
    {
        unset($this->merchantInfo);
    }

    /**
     * Generated from protobuf field <code>.finance.SingleMerchantQuery merchantInfo = 1;</code>
     * @param \Yinge\Grpc\Finance\SingleMerchantQuery $var
     * @return $this
     */
    public function setMerchantInfo($var)
    {
        GPBUtil::checkMessage($var, \Yinge\Grpc\Finance\SingleMerchantQuery::class);
        $this->merchantInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string clientIp = 2;</code>
     * @return string
     */
    public function getClientIp()
    {
        return $this->clientIp;
    }

    /**
     * Generated from protobuf field <code>string clientIp = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setClientIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientIp = $var;

        return $this;
    }

}

