<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Yinge\Grpc\Finance;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finance.AuthInfo</code>
 */
class AuthInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string mobile = 3;</code>
     */
    protected $mobile = '';
    /**
     * Generated from protobuf field <code>string idNumber = 4;</code>
     */
    protected $idNumber = '';
    /**
     * Generated from protobuf field <code>int64 authTime = 5;</code>
     */
    protected $authTime = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type string $name
     *     @type string $mobile
     *     @type string $idNumber
     *     @type int|string $authTime
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Finance\GPBMetadata\Finance::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string mobile = 3;</code>
     * @return string
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     * Generated from protobuf field <code>string mobile = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobile = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string idNumber = 4;</code>
     * @return string
     */
    public function getIdNumber()
    {
        return $this->idNumber;
    }

    /**
     * Generated from protobuf field <code>string idNumber = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setIdNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->idNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 authTime = 5;</code>
     * @return int|string
     */
    public function getAuthTime()
    {
        return $this->authTime;
    }

    /**
     * Generated from protobuf field <code>int64 authTime = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAuthTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->authTime = $var;

        return $this;
    }

}

