<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Yinge\Grpc\Finance;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finance.BankBind</code>
 */
class BankBind extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 bankId = 1;</code>
     */
    protected $bankId = 0;
    /**
     * Generated from protobuf field <code>string bankName = 2;</code>
     */
    protected $bankName = '';
    /**
     * Generated from protobuf field <code>string accountName = 3;</code>
     */
    protected $accountName = '';
    /**
     * Generated from protobuf field <code>string accountNo = 4;</code>
     */
    protected $accountNo = '';
    /**
     * Generated from protobuf field <code>string mobile = 5;</code>
     */
    protected $mobile = '';
    /**
     * Generated from protobuf field <code>int64 idType = 6;</code>
     */
    protected $idType = 0;
    /**
     * Generated from protobuf field <code>string idNumber = 7;</code>
     */
    protected $idNumber = '';
    /**
     * Generated from protobuf field <code>int64 status = 8;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>int64 bindingTime = 9;</code>
     */
    protected $bindingTime = 0;
    /**
     * Generated from protobuf field <code>int64 acctId = 10;</code>
     */
    protected $acctId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $bankId
     *     @type string $bankName
     *     @type string $accountName
     *     @type string $accountNo
     *     @type string $mobile
     *     @type int|string $idType
     *     @type string $idNumber
     *     @type int|string $status
     *     @type int|string $bindingTime
     *     @type int|string $acctId
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Finance\GPBMetadata\Finance::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 bankId = 1;</code>
     * @return int|string
     */
    public function getBankId()
    {
        return $this->bankId;
    }

    /**
     * Generated from protobuf field <code>int64 bankId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBankId($var)
    {
        GPBUtil::checkInt64($var);
        $this->bankId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bankName = 2;</code>
     * @return string
     */
    public function getBankName()
    {
        return $this->bankName;
    }

    /**
     * Generated from protobuf field <code>string bankName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBankName($var)
    {
        GPBUtil::checkString($var, True);
        $this->bankName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string accountName = 3;</code>
     * @return string
     */
    public function getAccountName()
    {
        return $this->accountName;
    }

    /**
     * Generated from protobuf field <code>string accountName = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAccountName($var)
    {
        GPBUtil::checkString($var, True);
        $this->accountName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string accountNo = 4;</code>
     * @return string
     */
    public function getAccountNo()
    {
        return $this->accountNo;
    }

    /**
     * Generated from protobuf field <code>string accountNo = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAccountNo($var)
    {
        GPBUtil::checkString($var, True);
        $this->accountNo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string mobile = 5;</code>
     * @return string
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     * Generated from protobuf field <code>string mobile = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobile = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 idType = 6;</code>
     * @return int|string
     */
    public function getIdType()
    {
        return $this->idType;
    }

    /**
     * Generated from protobuf field <code>int64 idType = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIdType($var)
    {
        GPBUtil::checkInt64($var);
        $this->idType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string idNumber = 7;</code>
     * @return string
     */
    public function getIdNumber()
    {
        return $this->idNumber;
    }

    /**
     * Generated from protobuf field <code>string idNumber = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setIdNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->idNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 status = 8;</code>
     * @return int|string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>int64 status = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt64($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 bindingTime = 9;</code>
     * @return int|string
     */
    public function getBindingTime()
    {
        return $this->bindingTime;
    }

    /**
     * Generated from protobuf field <code>int64 bindingTime = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBindingTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->bindingTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 acctId = 10;</code>
     * @return int|string
     */
    public function getAcctId()
    {
        return $this->acctId;
    }

    /**
     * Generated from protobuf field <code>int64 acctId = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAcctId($var)
    {
        GPBUtil::checkInt64($var);
        $this->acctId = $var;

        return $this;
    }

}

