<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Yinge\Grpc\Finance;

if (false) {
    /**
     * This class is deprecated. Use Yinge\Grpc\Finance\BankListResponse\Item instead.
     * @deprecated
     */
    class BankListResponse_Item {}
}
class_exists(BankListResponse\Item::class);
@trigger_error('Yinge\Grpc\Finance\BankListResponse_Item is deprecated and will be removed in the next major release. Use Yinge\Grpc\Finance\BankListResponse\Item instead', E_USER_DEPRECATED);

