<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Yinge\Grpc\Finance;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finance.BatchRules</code>
 */
class BatchRules extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated int64 ids = 1;</code>
     */
    private $ids;
    /**
     * Generated from protobuf field <code>map<int64, int64> rules = 2;</code>
     */
    private $rules;
    /**
     * Generated from protobuf field <code>int64 operator = 3;</code>
     */
    protected $operator = 0;
    /**
     * Generated from protobuf field <code>int64 method = 4;</code>
     */
    protected $method = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $ids
     *     @type array|\Google\Protobuf\Internal\MapField $rules
     *     @type int|string $operator
     *     @type int|string $method
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Finance\GPBMetadata\Finance::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated int64 ids = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIds()
    {
        return $this->ids;
    }

    /**
     * Generated from protobuf field <code>repeated int64 ids = 1;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->ids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<int64, int64> rules = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getRules()
    {
        return $this->rules;
    }

    /**
     * Generated from protobuf field <code>map<int64, int64> rules = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setRules($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT64, \Google\Protobuf\Internal\GPBType::INT64);
        $this->rules = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 operator = 3;</code>
     * @return int|string
     */
    public function getOperator()
    {
        return $this->operator;
    }

    /**
     * Generated from protobuf field <code>int64 operator = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOperator($var)
    {
        GPBUtil::checkInt64($var);
        $this->operator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 method = 4;</code>
     * @return int|string
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * Generated from protobuf field <code>int64 method = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMethod($var)
    {
        GPBUtil::checkInt64($var);
        $this->method = $var;

        return $this;
    }

}

