<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Yinge\Grpc\Finance;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finance.BatchUpdateResult</code>
 */
class BatchUpdateResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 succ = 1;</code>
     */
    protected $succ = 0;
    /**
     * Generated from protobuf field <code>int64 fail = 2;</code>
     */
    protected $fail = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $succ
     *     @type int|string $fail
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Finance\GPBMetadata\Finance::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 succ = 1;</code>
     * @return int|string
     */
    public function getSucc()
    {
        return $this->succ;
    }

    /**
     * Generated from protobuf field <code>int64 succ = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSucc($var)
    {
        GPBUtil::checkInt64($var);
        $this->succ = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 fail = 2;</code>
     * @return int|string
     */
    public function getFail()
    {
        return $this->fail;
    }

    /**
     * Generated from protobuf field <code>int64 fail = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFail($var)
    {
        GPBUtil::checkInt64($var);
        $this->fail = $var;

        return $this;
    }

}

