<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Yinge\Grpc\Finance;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finance.BindRequest</code>
 */
class BindRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 globalType = 1;</code>
     */
    protected $globalType = 0;
    /**
     * Generated from protobuf field <code>string globalId = 2;</code>
     */
    protected $globalId = '';
    /**
     * Generated from protobuf field <code>string accountName = 3;</code>
     */
    protected $accountName = '';
    /**
     * Generated from protobuf field <code>string accountNo = 4;</code>
     */
    protected $accountNo = '';
    /**
     * Generated from protobuf field <code>int64 bankId = 5;</code>
     */
    protected $bankId = 0;
    /**
     * Generated from protobuf field <code>string mobile = 6;</code>
     */
    protected $mobile = '';
    /**
     * Generated from protobuf field <code>int64 method = 7;</code>
     */
    protected $method = 0;
    /**
     * Generated from protobuf field <code>int64 originId = 8;</code>
     */
    protected $originId = 0;
    /**
     * Generated from protobuf field <code>int64 merchantType = 9;</code>
     */
    protected $merchantType = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $globalType
     *     @type string $globalId
     *     @type string $accountName
     *     @type string $accountNo
     *     @type int|string $bankId
     *     @type string $mobile
     *     @type int|string $method
     *     @type int|string $originId
     *     @type int|string $merchantType
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Finance\GPBMetadata\Finance::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 globalType = 1;</code>
     * @return int|string
     */
    public function getGlobalType()
    {
        return $this->globalType;
    }

    /**
     * Generated from protobuf field <code>int64 globalType = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGlobalType($var)
    {
        GPBUtil::checkInt64($var);
        $this->globalType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string globalId = 2;</code>
     * @return string
     */
    public function getGlobalId()
    {
        return $this->globalId;
    }

    /**
     * Generated from protobuf field <code>string globalId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setGlobalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->globalId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string accountName = 3;</code>
     * @return string
     */
    public function getAccountName()
    {
        return $this->accountName;
    }

    /**
     * Generated from protobuf field <code>string accountName = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAccountName($var)
    {
        GPBUtil::checkString($var, True);
        $this->accountName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string accountNo = 4;</code>
     * @return string
     */
    public function getAccountNo()
    {
        return $this->accountNo;
    }

    /**
     * Generated from protobuf field <code>string accountNo = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAccountNo($var)
    {
        GPBUtil::checkString($var, True);
        $this->accountNo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 bankId = 5;</code>
     * @return int|string
     */
    public function getBankId()
    {
        return $this->bankId;
    }

    /**
     * Generated from protobuf field <code>int64 bankId = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBankId($var)
    {
        GPBUtil::checkInt64($var);
        $this->bankId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string mobile = 6;</code>
     * @return string
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     * Generated from protobuf field <code>string mobile = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobile = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 method = 7;</code>
     * @return int|string
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * Generated from protobuf field <code>int64 method = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMethod($var)
    {
        GPBUtil::checkInt64($var);
        $this->method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 originId = 8;</code>
     * @return int|string
     */
    public function getOriginId()
    {
        return $this->originId;
    }

    /**
     * Generated from protobuf field <code>int64 originId = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOriginId($var)
    {
        GPBUtil::checkInt64($var);
        $this->originId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 merchantType = 9;</code>
     * @return int|string
     */
    public function getMerchantType()
    {
        return $this->merchantType;
    }

    /**
     * Generated from protobuf field <code>int64 merchantType = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMerchantType($var)
    {
        GPBUtil::checkInt64($var);
        $this->merchantType = $var;

        return $this;
    }

}

