<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Yinge\Grpc\Finance;

if (false) {
    /**
     * This class is deprecated. Use Yinge\Grpc\Finance\BindBankRequest\AccountType instead.
     * @deprecated
     */
    class BindBankRequest_AccountType {}
}
class_exists(BindBankRequest\AccountType::class);
@trigger_error('Yinge\Grpc\Finance\BindBankRequest_AccountType is deprecated and will be removed in the next major release. Use Yinge\Grpc\Finance\BindBankRequest\AccountType instead', E_USER_DEPRECATED);

