<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Yinge\Grpc\Finance;

if (false) {
    /**
     * This class is deprecated. Use Yinge\Grpc\Finance\FrozenAmountResponse\Item instead.
     * @deprecated
     */
    class FrozenAmountResponse_Item {}
}
class_exists(FrozenAmountResponse\Item::class);
@trigger_error('Yinge\Grpc\Finance\FrozenAmountResponse_Item is deprecated and will be removed in the next major release. Use Yinge\Grpc\Finance\FrozenAmountResponse\Item instead', E_USER_DEPRECATED);

