<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Yinge\Grpc\Finance;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finance.MemberTransferRequest</code>
 */
class MemberTransferRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 inId = 1;</code>
     */
    protected $inId = 0;
    /**
     * Generated from protobuf field <code>int64 inType = 2;</code>
     */
    protected $inType = 0;
    /**
     * Generated from protobuf field <code>int64 outId = 3;</code>
     */
    protected $outId = 0;
    /**
     * Generated from protobuf field <code>int64 outType = 4;</code>
     */
    protected $outType = 0;
    /**
     * Generated from protobuf field <code>uint32 amount = 5;</code>
     */
    protected $amount = 0;
    /**
     * Generated from protobuf field <code>string remark = 6;</code>
     */
    protected $remark = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $inId
     *     @type int|string $inType
     *     @type int|string $outId
     *     @type int|string $outType
     *     @type int $amount
     *     @type string $remark
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Finance\GPBMetadata\Finance::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 inId = 1;</code>
     * @return int|string
     */
    public function getInId()
    {
        return $this->inId;
    }

    /**
     * Generated from protobuf field <code>int64 inId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setInId($var)
    {
        GPBUtil::checkInt64($var);
        $this->inId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 inType = 2;</code>
     * @return int|string
     */
    public function getInType()
    {
        return $this->inType;
    }

    /**
     * Generated from protobuf field <code>int64 inType = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setInType($var)
    {
        GPBUtil::checkInt64($var);
        $this->inType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 outId = 3;</code>
     * @return int|string
     */
    public function getOutId()
    {
        return $this->outId;
    }

    /**
     * Generated from protobuf field <code>int64 outId = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOutId($var)
    {
        GPBUtil::checkInt64($var);
        $this->outId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 outType = 4;</code>
     * @return int|string
     */
    public function getOutType()
    {
        return $this->outType;
    }

    /**
     * Generated from protobuf field <code>int64 outType = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOutType($var)
    {
        GPBUtil::checkInt64($var);
        $this->outType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 amount = 5;</code>
     * @return int
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>uint32 amount = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkUint32($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string remark = 6;</code>
     * @return string
     */
    public function getRemark()
    {
        return $this->remark;
    }

    /**
     * Generated from protobuf field <code>string remark = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setRemark($var)
    {
        GPBUtil::checkString($var, True);
        $this->remark = $var;

        return $this;
    }

}

