<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Yinge\Grpc\Finance;

if (false) {
    /**
     * This class is deprecated. Use Yinge\Grpc\Finance\MerchantListResponse\Account instead.
     * @deprecated
     */
    class MerchantListResponse_Account {}
}
class_exists(MerchantListResponse\Account::class);
@trigger_error('Yinge\Grpc\Finance\MerchantListResponse_Account is deprecated and will be removed in the next major release. Use Yinge\Grpc\Finance\MerchantListResponse\Account instead', E_USER_DEPRECATED);

