<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Yinge\Grpc\Finance;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finance.MerchantListResponse</code>
 */
class MerchantListResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .finance.MerchantListResponse.Items list = 1;</code>
     */
    private $list;
    /**
     * Generated from protobuf field <code>int64 totalCount = 2;</code>
     */
    protected $totalCount = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Yinge\Grpc\Finance\MerchantListResponse\Items[]|\Google\Protobuf\Internal\RepeatedField $list
     *     @type int|string $totalCount
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Finance\GPBMetadata\Finance::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .finance.MerchantListResponse.Items list = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getList()
    {
        return $this->list;
    }

    /**
     * Generated from protobuf field <code>repeated .finance.MerchantListResponse.Items list = 1;</code>
     * @param \Yinge\Grpc\Finance\MerchantListResponse\Items[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Yinge\Grpc\Finance\MerchantListResponse\Items::class);
        $this->list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 totalCount = 2;</code>
     * @return int|string
     */
    public function getTotalCount()
    {
        return $this->totalCount;
    }

    /**
     * Generated from protobuf field <code>int64 totalCount = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->totalCount = $var;

        return $this;
    }

}

