<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Yinge\Grpc\Finance;

if (false) {
    /**
     * This class is deprecated. Use Yinge\Grpc\Finance\MerchantListResponse\Items instead.
     * @deprecated
     */
    class MerchantListResponse_Items {}
}
class_exists(MerchantListResponse\Items::class);
@trigger_error('Yinge\Grpc\Finance\MerchantListResponse_Items is deprecated and will be removed in the next major release. Use Yinge\Grpc\Finance\MerchantListResponse\Items instead', E_USER_DEPRECATED);

