<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Yinge\Grpc\Finance;

if (false) {
    /**
     * This class is deprecated. Use Yinge\Grpc\Finance\MerchantListResponse\BankBind instead.
     * @deprecated
     */
    class MerchantListResponse_BankBind {}
}
class_exists(MerchantListResponse\BankBind::class);
@trigger_error('Yinge\Grpc\Finance\MerchantListResponse_BankBind is deprecated and will be removed in the next major release. Use Yinge\Grpc\Finance\MerchantListResponse\BankBind instead', E_USER_DEPRECATED);

