<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance_transaction.proto

namespace Yinge\Grpc\Finance;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finance.RefundRequest</code>
 */
class RefundRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 paymentChannel = 1;</code>
     */
    protected $paymentChannel = 0;
    /**
     * Generated from protobuf field <code>string tradeNo = 2;</code>
     */
    protected $tradeNo = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $paymentChannel
     *     @type string $tradeNo
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Finance\GPBMetadata\FinanceTransaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 paymentChannel = 1;</code>
     * @return int|string
     */
    public function getPaymentChannel()
    {
        return $this->paymentChannel;
    }

    /**
     * Generated from protobuf field <code>int64 paymentChannel = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPaymentChannel($var)
    {
        GPBUtil::checkInt64($var);
        $this->paymentChannel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tradeNo = 2;</code>
     * @return string
     */
    public function getTradeNo()
    {
        return $this->tradeNo;
    }

    /**
     * Generated from protobuf field <code>string tradeNo = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTradeNo($var)
    {
        GPBUtil::checkString($var, True);
        $this->tradeNo = $var;

        return $this;
    }

}

