<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Yinge\Grpc\Finance;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finance.ReportBindCodeRequest</code>
 */
class ReportBindCodeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>int64 merchantType = 2;</code>
     */
    protected $merchantType = 0;
    /**
     * Generated from protobuf field <code>string code = 3;</code>
     */
    protected $code = '';
    /**
     * Generated from protobuf field <code>string acctNo = 4;</code>
     */
    protected $acctNo = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type int|string $merchantType
     *     @type string $code
     *     @type string $acctNo
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Finance\GPBMetadata\Finance::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 merchantType = 2;</code>
     * @return int|string
     */
    public function getMerchantType()
    {
        return $this->merchantType;
    }

    /**
     * Generated from protobuf field <code>int64 merchantType = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMerchantType($var)
    {
        GPBUtil::checkInt64($var);
        $this->merchantType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string code = 3;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>string code = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string acctNo = 4;</code>
     * @return string
     */
    public function getAcctNo()
    {
        return $this->acctNo;
    }

    /**
     * Generated from protobuf field <code>string acctNo = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAcctNo($var)
    {
        GPBUtil::checkString($var, True);
        $this->acctNo = $var;

        return $this;
    }

}

