<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Yinge\Grpc\Finance;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finance.SettleRequest</code>
 */
class SettleRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>int64 merchantType = 2;</code>
     */
    protected $merchantType = 0;
    /**
     * Generated from protobuf field <code>int64 amount = 3;</code>
     */
    protected $amount = 0;
    /**
     * Generated from protobuf field <code>string remark = 4;</code>
     */
    protected $remark = '';
    /**
     * Generated from protobuf field <code>int64 reparation = 5;</code>
     */
    protected $reparation = 0;
    /**
     * Generated from protobuf field <code>string reparationRemark = 6;</code>
     */
    protected $reparationRemark = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type int|string $merchantType
     *     @type int|string $amount
     *     @type string $remark
     *     @type int|string $reparation
     *     @type string $reparationRemark
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Finance\GPBMetadata\Finance::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 merchantType = 2;</code>
     * @return int|string
     */
    public function getMerchantType()
    {
        return $this->merchantType;
    }

    /**
     * Generated from protobuf field <code>int64 merchantType = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMerchantType($var)
    {
        GPBUtil::checkInt64($var);
        $this->merchantType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 amount = 3;</code>
     * @return int|string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>int64 amount = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string remark = 4;</code>
     * @return string
     */
    public function getRemark()
    {
        return $this->remark;
    }

    /**
     * Generated from protobuf field <code>string remark = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setRemark($var)
    {
        GPBUtil::checkString($var, True);
        $this->remark = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 reparation = 5;</code>
     * @return int|string
     */
    public function getReparation()
    {
        return $this->reparation;
    }

    /**
     * Generated from protobuf field <code>int64 reparation = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setReparation($var)
    {
        GPBUtil::checkInt64($var);
        $this->reparation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string reparationRemark = 6;</code>
     * @return string
     */
    public function getReparationRemark()
    {
        return $this->reparationRemark;
    }

    /**
     * Generated from protobuf field <code>string reparationRemark = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setReparationRemark($var)
    {
        GPBUtil::checkString($var, True);
        $this->reparationRemark = $var;

        return $this;
    }

}

