<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Yinge\Grpc\Finance;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finance.SettleRequest</code>
 */
class SettleRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 receiverId = 1;</code>
     */
    protected $receiverId = 0;
    /**
     * Generated from protobuf field <code>int64 receiverType = 2;</code>
     */
    protected $receiverType = 0;
    /**
     * Generated from protobuf field <code>int64 undertakerId = 3;</code>
     */
    protected $undertakerId = 0;
    /**
     * Generated from protobuf field <code>int64 undertakerType = 4;</code>
     */
    protected $undertakerType = 0;
    /**
     * Generated from protobuf field <code>int64 settle = 5;</code>
     */
    protected $settle = 0;
    /**
     * Generated from protobuf field <code>int64 subsidy = 6;</code>
     */
    protected $subsidy = 0;
    /**
     * Generated from protobuf field <code>int64 reparation = 7;</code>
     */
    protected $reparation = 0;
    /**
     * Generated from protobuf field <code>string billCycle = 8;</code>
     */
    protected $billCycle = '';
    /**
     * Generated from protobuf field <code>string reparationCycle = 10;</code>
     */
    protected $reparationCycle = '';
    /**
     * Generated from protobuf field <code>int64 billId = 9;</code>
     */
    protected $billId = 0;
    /**
     * Generated from protobuf field <code>int64 reparationId = 11;</code>
     */
    protected $reparationId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $receiverId
     *     @type int|string $receiverType
     *     @type int|string $undertakerId
     *     @type int|string $undertakerType
     *     @type int|string $settle
     *     @type int|string $subsidy
     *     @type int|string $reparation
     *     @type string $billCycle
     *     @type string $reparationCycle
     *     @type int|string $billId
     *     @type int|string $reparationId
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Finance\GPBMetadata\Finance::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 receiverId = 1;</code>
     * @return int|string
     */
    public function getReceiverId()
    {
        return $this->receiverId;
    }

    /**
     * Generated from protobuf field <code>int64 receiverId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setReceiverId($var)
    {
        GPBUtil::checkInt64($var);
        $this->receiverId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 receiverType = 2;</code>
     * @return int|string
     */
    public function getReceiverType()
    {
        return $this->receiverType;
    }

    /**
     * Generated from protobuf field <code>int64 receiverType = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setReceiverType($var)
    {
        GPBUtil::checkInt64($var);
        $this->receiverType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 undertakerId = 3;</code>
     * @return int|string
     */
    public function getUndertakerId()
    {
        return $this->undertakerId;
    }

    /**
     * Generated from protobuf field <code>int64 undertakerId = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUndertakerId($var)
    {
        GPBUtil::checkInt64($var);
        $this->undertakerId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 undertakerType = 4;</code>
     * @return int|string
     */
    public function getUndertakerType()
    {
        return $this->undertakerType;
    }

    /**
     * Generated from protobuf field <code>int64 undertakerType = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUndertakerType($var)
    {
        GPBUtil::checkInt64($var);
        $this->undertakerType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 settle = 5;</code>
     * @return int|string
     */
    public function getSettle()
    {
        return $this->settle;
    }

    /**
     * Generated from protobuf field <code>int64 settle = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSettle($var)
    {
        GPBUtil::checkInt64($var);
        $this->settle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 subsidy = 6;</code>
     * @return int|string
     */
    public function getSubsidy()
    {
        return $this->subsidy;
    }

    /**
     * Generated from protobuf field <code>int64 subsidy = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSubsidy($var)
    {
        GPBUtil::checkInt64($var);
        $this->subsidy = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 reparation = 7;</code>
     * @return int|string
     */
    public function getReparation()
    {
        return $this->reparation;
    }

    /**
     * Generated from protobuf field <code>int64 reparation = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setReparation($var)
    {
        GPBUtil::checkInt64($var);
        $this->reparation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string billCycle = 8;</code>
     * @return string
     */
    public function getBillCycle()
    {
        return $this->billCycle;
    }

    /**
     * Generated from protobuf field <code>string billCycle = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setBillCycle($var)
    {
        GPBUtil::checkString($var, True);
        $this->billCycle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string reparationCycle = 10;</code>
     * @return string
     */
    public function getReparationCycle()
    {
        return $this->reparationCycle;
    }

    /**
     * Generated from protobuf field <code>string reparationCycle = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setReparationCycle($var)
    {
        GPBUtil::checkString($var, True);
        $this->reparationCycle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 billId = 9;</code>
     * @return int|string
     */
    public function getBillId()
    {
        return $this->billId;
    }

    /**
     * Generated from protobuf field <code>int64 billId = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBillId($var)
    {
        GPBUtil::checkInt64($var);
        $this->billId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 reparationId = 11;</code>
     * @return int|string
     */
    public function getReparationId()
    {
        return $this->reparationId;
    }

    /**
     * Generated from protobuf field <code>int64 reparationId = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setReparationId($var)
    {
        GPBUtil::checkInt64($var);
        $this->reparationId = $var;

        return $this;
    }

}

