<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance_transaction.proto

namespace Yinge\Grpc\Finance;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finance.SplitRequest</code>
 */
class SplitRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string orderId = 1;</code>
     */
    protected $orderId = '';
    /**
     * Generated from protobuf field <code>int64 paymentChannel = 2;</code>
     */
    protected $paymentChannel = 0;
    /**
     * Generated from protobuf field <code>int64 totalAmount = 3;</code>
     */
    protected $totalAmount = 0;
    /**
     * Generated from protobuf field <code>string tradeNo = 4;</code>
     */
    protected $tradeNo = '';
    /**
     * Generated from protobuf field <code>repeated .finance.SplitRequest.SplitSubOrder SubOrders = 5;</code>
     */
    private $SubOrders;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $orderId
     *     @type int|string $paymentChannel
     *     @type int|string $totalAmount
     *     @type string $tradeNo
     *     @type \Yinge\Grpc\Finance\SplitRequest\SplitSubOrder[]|\Google\Protobuf\Internal\RepeatedField $SubOrders
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Finance\GPBMetadata\FinanceTransaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string orderId = 1;</code>
     * @return string
     */
    public function getOrderId()
    {
        return $this->orderId;
    }

    /**
     * Generated from protobuf field <code>string orderId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderId($var)
    {
        GPBUtil::checkString($var, True);
        $this->orderId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 paymentChannel = 2;</code>
     * @return int|string
     */
    public function getPaymentChannel()
    {
        return $this->paymentChannel;
    }

    /**
     * Generated from protobuf field <code>int64 paymentChannel = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPaymentChannel($var)
    {
        GPBUtil::checkInt64($var);
        $this->paymentChannel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 totalAmount = 3;</code>
     * @return int|string
     */
    public function getTotalAmount()
    {
        return $this->totalAmount;
    }

    /**
     * Generated from protobuf field <code>int64 totalAmount = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->totalAmount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tradeNo = 4;</code>
     * @return string
     */
    public function getTradeNo()
    {
        return $this->tradeNo;
    }

    /**
     * Generated from protobuf field <code>string tradeNo = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTradeNo($var)
    {
        GPBUtil::checkString($var, True);
        $this->tradeNo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .finance.SplitRequest.SplitSubOrder SubOrders = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSubOrders()
    {
        return $this->SubOrders;
    }

    /**
     * Generated from protobuf field <code>repeated .finance.SplitRequest.SplitSubOrder SubOrders = 5;</code>
     * @param \Yinge\Grpc\Finance\SplitRequest\SplitSubOrder[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSubOrders($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Yinge\Grpc\Finance\SplitRequest\SplitSubOrder::class);
        $this->SubOrders = $arr;

        return $this;
    }

}

