<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Yinge\Grpc\Finance;

if (false) {
    /**
     * This class is deprecated. Use Yinge\Grpc\Finance\SplitRuleHistories\UpdateHistory instead.
     * @deprecated
     */
    class SplitRuleHistories_UpdateHistory {}
}
class_exists(SplitRuleHistories\UpdateHistory::class);
@trigger_error('Yinge\Grpc\Finance\SplitRuleHistories_UpdateHistory is deprecated and will be removed in the next major release. Use Yinge\Grpc\Finance\SplitRuleHistories\UpdateHistory instead', E_USER_DEPRECATED);

