<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Yinge\Grpc\Finance;

if (false) {
    /**
     * This class is deprecated. Use Yinge\Grpc\Finance\SplitListResponse\SplitInfo instead.
     * @deprecated
     */
    class SplitListResponse_SplitInfo {}
}
class_exists(SplitListResponse\SplitInfo::class);
@trigger_error('Yinge\Grpc\Finance\SplitListResponse_SplitInfo is deprecated and will be removed in the next major release. Use Yinge\Grpc\Finance\SplitListResponse\SplitInfo instead', E_USER_DEPRECATED);

