<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Yinge\Grpc\Finance;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finance.SplitDetail</code>
 */
class SplitDetail extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 orderId = 1;</code>
     */
    protected $orderId = 0;
    /**
     * Generated from protobuf field <code>int64 merchantId = 2;</code>
     */
    protected $merchantId = 0;
    /**
     * Generated from protobuf field <code>int64 merchantOriginId = 3;</code>
     */
    protected $merchantOriginId = 0;
    /**
     * Generated from protobuf field <code>int64 merchantType = 4;</code>
     */
    protected $merchantType = 0;
    /**
     * Generated from protobuf field <code>int64 amount = 5;</code>
     */
    protected $amount = 0;
    /**
     * Generated from protobuf field <code>int64 transFee = 6;</code>
     */
    protected $transFee = 0;
    /**
     * Generated from protobuf field <code>int64 rechargeStatus = 7;</code>
     */
    protected $rechargeStatus = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $orderId
     *     @type int|string $merchantId
     *     @type int|string $merchantOriginId
     *     @type int|string $merchantType
     *     @type int|string $amount
     *     @type int|string $transFee
     *     @type int|string $rechargeStatus
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Finance\GPBMetadata\Finance::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 orderId = 1;</code>
     * @return int|string
     */
    public function getOrderId()
    {
        return $this->orderId;
    }

    /**
     * Generated from protobuf field <code>int64 orderId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOrderId($var)
    {
        GPBUtil::checkInt64($var);
        $this->orderId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 merchantId = 2;</code>
     * @return int|string
     */
    public function getMerchantId()
    {
        return $this->merchantId;
    }

    /**
     * Generated from protobuf field <code>int64 merchantId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMerchantId($var)
    {
        GPBUtil::checkInt64($var);
        $this->merchantId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 merchantOriginId = 3;</code>
     * @return int|string
     */
    public function getMerchantOriginId()
    {
        return $this->merchantOriginId;
    }

    /**
     * Generated from protobuf field <code>int64 merchantOriginId = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMerchantOriginId($var)
    {
        GPBUtil::checkInt64($var);
        $this->merchantOriginId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 merchantType = 4;</code>
     * @return int|string
     */
    public function getMerchantType()
    {
        return $this->merchantType;
    }

    /**
     * Generated from protobuf field <code>int64 merchantType = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMerchantType($var)
    {
        GPBUtil::checkInt64($var);
        $this->merchantType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 amount = 5;</code>
     * @return int|string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>int64 amount = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 transFee = 6;</code>
     * @return int|string
     */
    public function getTransFee()
    {
        return $this->transFee;
    }

    /**
     * Generated from protobuf field <code>int64 transFee = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTransFee($var)
    {
        GPBUtil::checkInt64($var);
        $this->transFee = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 rechargeStatus = 7;</code>
     * @return int|string
     */
    public function getRechargeStatus()
    {
        return $this->rechargeStatus;
    }

    /**
     * Generated from protobuf field <code>int64 rechargeStatus = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRechargeStatus($var)
    {
        GPBUtil::checkInt64($var);
        $this->rechargeStatus = $var;

        return $this;
    }

}

