<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance_transaction.proto

namespace Yinge\Grpc\Finance;

if (false) {
    /**
     * This class is deprecated. Use Yinge\Grpc\Finance\SplitRequest\SplitSubOrder instead.
     * @deprecated
     */
    class SplitRequest_SplitSubOrder {}
}
class_exists(SplitRequest\SplitSubOrder::class);
@trigger_error('Yinge\Grpc\Finance\SplitRequest_SplitSubOrder is deprecated and will be removed in the next major release. Use Yinge\Grpc\Finance\SplitRequest\SplitSubOrder instead', E_USER_DEPRECATED);

