<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Yinge\Grpc\Finance;

if (false) {
    /**
     * This class is deprecated. Use Yinge\Grpc\Finance\SplitRulesResponse\SplitRule instead.
     * @deprecated
     */
    class SplitRulesResponse_SplitRule {}
}
class_exists(SplitRulesResponse\SplitRule::class);
@trigger_error('Yinge\Grpc\Finance\SplitRulesResponse_SplitRule is deprecated and will be removed in the next major release. Use Yinge\Grpc\Finance\SplitRulesResponse\SplitRule instead', E_USER_DEPRECATED);

