<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Yinge\Grpc\Finance;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finance.SplitBatchQueryRequest</code>
 */
class SplitBatchQueryRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string orderIds = 1;</code>
     */
    protected $orderIds = '';
    /**
     * Generated from protobuf field <code>int64 merchantType = 2;</code>
     */
    protected $merchantType = 0;
    /**
     * Generated from protobuf field <code>int64 targetId = 3;</code>
     */
    protected $targetId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $orderIds
     *     @type int|string $merchantType
     *     @type int|string $targetId
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Finance\GPBMetadata\Finance::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string orderIds = 1;</code>
     * @return string
     */
    public function getOrderIds()
    {
        return $this->orderIds;
    }

    /**
     * Generated from protobuf field <code>string orderIds = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderIds($var)
    {
        GPBUtil::checkString($var, True);
        $this->orderIds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 merchantType = 2;</code>
     * @return int|string
     */
    public function getMerchantType()
    {
        return $this->merchantType;
    }

    /**
     * Generated from protobuf field <code>int64 merchantType = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMerchantType($var)
    {
        GPBUtil::checkInt64($var);
        $this->merchantType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 targetId = 3;</code>
     * @return int|string
     */
    public function getTargetId()
    {
        return $this->targetId;
    }

    /**
     * Generated from protobuf field <code>int64 targetId = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTargetId($var)
    {
        GPBUtil::checkInt64($var);
        $this->targetId = $var;

        return $this;
    }

}

