<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Yinge\Grpc\Finance;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finance.SplitListRequest</code>
 */
class SplitListRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 orderId = 1;</code>
     */
    protected $orderId = 0;
    /**
     * Generated from protobuf field <code>int64 startTime = 2;</code>
     */
    protected $startTime = 0;
    /**
     * Generated from protobuf field <code>int64 stopTime = 3;</code>
     */
    protected $stopTime = 0;
    /**
     * Generated from protobuf field <code>int64 page = 4;</code>
     */
    protected $page = 0;
    /**
     * Generated from protobuf field <code>repeated .finance.SingleMerchantQuery merchants = 5;</code>
     */
    private $merchants;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $orderId
     *     @type int|string $startTime
     *     @type int|string $stopTime
     *     @type int|string $page
     *     @type \Yinge\Grpc\Finance\SingleMerchantQuery[]|\Google\Protobuf\Internal\RepeatedField $merchants
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Finance\GPBMetadata\Finance::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 orderId = 1;</code>
     * @return int|string
     */
    public function getOrderId()
    {
        return $this->orderId;
    }

    /**
     * Generated from protobuf field <code>int64 orderId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOrderId($var)
    {
        GPBUtil::checkInt64($var);
        $this->orderId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 startTime = 2;</code>
     * @return int|string
     */
    public function getStartTime()
    {
        return $this->startTime;
    }

    /**
     * Generated from protobuf field <code>int64 startTime = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->startTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 stopTime = 3;</code>
     * @return int|string
     */
    public function getStopTime()
    {
        return $this->stopTime;
    }

    /**
     * Generated from protobuf field <code>int64 stopTime = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStopTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->stopTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 page = 4;</code>
     * @return int|string
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * Generated from protobuf field <code>int64 page = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt64($var);
        $this->page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .finance.SingleMerchantQuery merchants = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMerchants()
    {
        return $this->merchants;
    }

    /**
     * Generated from protobuf field <code>repeated .finance.SingleMerchantQuery merchants = 5;</code>
     * @param \Yinge\Grpc\Finance\SingleMerchantQuery[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMerchants($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Yinge\Grpc\Finance\SingleMerchantQuery::class);
        $this->merchants = $arr;

        return $this;
    }

}

