<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Yinge\Grpc\Finance;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finance.SubsidyRequest</code>
 */
class SubsidyRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 receiverId = 1;</code>
     */
    protected $receiverId = 0;
    /**
     * Generated from protobuf field <code>int64 receiverType = 6;</code>
     */
    protected $receiverType = 0;
    /**
     * Generated from protobuf field <code>int64 amount = 2;</code>
     */
    protected $amount = 0;
    /**
     * Generated from protobuf field <code>int64 undertakerId = 3;</code>
     */
    protected $undertakerId = 0;
    /**
     * Generated from protobuf field <code>int64 undertakerType = 7;</code>
     */
    protected $undertakerType = 0;
    /**
     * Generated from protobuf field <code>string remark = 4;</code>
     */
    protected $remark = '';
    /**
     * Generated from protobuf field <code>int64 relatedId = 5;</code>
     */
    protected $relatedId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $receiverId
     *     @type int|string $receiverType
     *     @type int|string $amount
     *     @type int|string $undertakerId
     *     @type int|string $undertakerType
     *     @type string $remark
     *     @type int|string $relatedId
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Finance\GPBMetadata\Finance::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 receiverId = 1;</code>
     * @return int|string
     */
    public function getReceiverId()
    {
        return $this->receiverId;
    }

    /**
     * Generated from protobuf field <code>int64 receiverId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setReceiverId($var)
    {
        GPBUtil::checkInt64($var);
        $this->receiverId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 receiverType = 6;</code>
     * @return int|string
     */
    public function getReceiverType()
    {
        return $this->receiverType;
    }

    /**
     * Generated from protobuf field <code>int64 receiverType = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setReceiverType($var)
    {
        GPBUtil::checkInt64($var);
        $this->receiverType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 amount = 2;</code>
     * @return int|string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>int64 amount = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 undertakerId = 3;</code>
     * @return int|string
     */
    public function getUndertakerId()
    {
        return $this->undertakerId;
    }

    /**
     * Generated from protobuf field <code>int64 undertakerId = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUndertakerId($var)
    {
        GPBUtil::checkInt64($var);
        $this->undertakerId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 undertakerType = 7;</code>
     * @return int|string
     */
    public function getUndertakerType()
    {
        return $this->undertakerType;
    }

    /**
     * Generated from protobuf field <code>int64 undertakerType = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUndertakerType($var)
    {
        GPBUtil::checkInt64($var);
        $this->undertakerType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string remark = 4;</code>
     * @return string
     */
    public function getRemark()
    {
        return $this->remark;
    }

    /**
     * Generated from protobuf field <code>string remark = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setRemark($var)
    {
        GPBUtil::checkString($var, True);
        $this->remark = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 relatedId = 5;</code>
     * @return int|string
     */
    public function getRelatedId()
    {
        return $this->relatedId;
    }

    /**
     * Generated from protobuf field <code>int64 relatedId = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRelatedId($var)
    {
        GPBUtil::checkInt64($var);
        $this->relatedId = $var;

        return $this;
    }

}

