<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance_transaction.proto

namespace Yinge\Grpc\Finance;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finance.TransferDetailResponse</code>
 */
class TransferDetailResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>int64 payerId = 2;</code>
     */
    protected $payerId = 0;
    /**
     * Generated from protobuf field <code>int64 payerType = 3;</code>
     */
    protected $payerType = 0;
    /**
     * Generated from protobuf field <code>string payerMobile = 4;</code>
     */
    protected $payerMobile = '';
    /**
     * Generated from protobuf field <code>int64 payeeId = 5;</code>
     */
    protected $payeeId = 0;
    /**
     * Generated from protobuf field <code>int64 payeeType = 6;</code>
     */
    protected $payeeType = 0;
    /**
     * Generated from protobuf field <code>string payeeMobile = 7;</code>
     */
    protected $payeeMobile = '';
    /**
     * Generated from protobuf field <code>int64 type = 8;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>int64 tradeTime = 9;</code>
     */
    protected $tradeTime = 0;
    /**
     * Generated from protobuf field <code>string remark = 10;</code>
     */
    protected $remark = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type int|string $payerId
     *     @type int|string $payerType
     *     @type string $payerMobile
     *     @type int|string $payeeId
     *     @type int|string $payeeType
     *     @type string $payeeMobile
     *     @type int|string $type
     *     @type int|string $tradeTime
     *     @type string $remark
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Finance\GPBMetadata\FinanceTransaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 payerId = 2;</code>
     * @return int|string
     */
    public function getPayerId()
    {
        return $this->payerId;
    }

    /**
     * Generated from protobuf field <code>int64 payerId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPayerId($var)
    {
        GPBUtil::checkInt64($var);
        $this->payerId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 payerType = 3;</code>
     * @return int|string
     */
    public function getPayerType()
    {
        return $this->payerType;
    }

    /**
     * Generated from protobuf field <code>int64 payerType = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPayerType($var)
    {
        GPBUtil::checkInt64($var);
        $this->payerType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string payerMobile = 4;</code>
     * @return string
     */
    public function getPayerMobile()
    {
        return $this->payerMobile;
    }

    /**
     * Generated from protobuf field <code>string payerMobile = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPayerMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->payerMobile = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 payeeId = 5;</code>
     * @return int|string
     */
    public function getPayeeId()
    {
        return $this->payeeId;
    }

    /**
     * Generated from protobuf field <code>int64 payeeId = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPayeeId($var)
    {
        GPBUtil::checkInt64($var);
        $this->payeeId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 payeeType = 6;</code>
     * @return int|string
     */
    public function getPayeeType()
    {
        return $this->payeeType;
    }

    /**
     * Generated from protobuf field <code>int64 payeeType = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPayeeType($var)
    {
        GPBUtil::checkInt64($var);
        $this->payeeType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string payeeMobile = 7;</code>
     * @return string
     */
    public function getPayeeMobile()
    {
        return $this->payeeMobile;
    }

    /**
     * Generated from protobuf field <code>string payeeMobile = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setPayeeMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->payeeMobile = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 type = 8;</code>
     * @return int|string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>int64 type = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt64($var);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 tradeTime = 9;</code>
     * @return int|string
     */
    public function getTradeTime()
    {
        return $this->tradeTime;
    }

    /**
     * Generated from protobuf field <code>int64 tradeTime = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTradeTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->tradeTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string remark = 10;</code>
     * @return string
     */
    public function getRemark()
    {
        return $this->remark;
    }

    /**
     * Generated from protobuf field <code>string remark = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setRemark($var)
    {
        GPBUtil::checkString($var, True);
        $this->remark = $var;

        return $this;
    }

}

