<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Yinge\Grpc\Finance;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finance.WithdrawListRequest</code>
 */
class WithdrawListRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 merchantType = 1;</code>
     */
    protected $merchantType = 0;
    /**
     * Generated from protobuf field <code>int64 originId = 2;</code>
     */
    protected $originId = 0;
    /**
     * Generated from protobuf field <code>int64 startTime = 3;</code>
     */
    protected $startTime = 0;
    /**
     * Generated from protobuf field <code>int64 stopTime = 4;</code>
     */
    protected $stopTime = 0;
    /**
     * Generated from protobuf field <code>int64 status = 5;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>int64 page = 6;</code>
     */
    protected $page = 0;
    /**
     * Generated from protobuf field <code>int64 pageSize = 7;</code>
     */
    protected $pageSize = 0;
    /**
     * Generated from protobuf field <code>int64 id = 8;</code>
     */
    protected $id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $merchantType
     *     @type int|string $originId
     *     @type int|string $startTime
     *     @type int|string $stopTime
     *     @type int|string $status
     *     @type int|string $page
     *     @type int|string $pageSize
     *     @type int|string $id
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Finance\GPBMetadata\Finance::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 merchantType = 1;</code>
     * @return int|string
     */
    public function getMerchantType()
    {
        return $this->merchantType;
    }

    /**
     * Generated from protobuf field <code>int64 merchantType = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMerchantType($var)
    {
        GPBUtil::checkInt64($var);
        $this->merchantType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 originId = 2;</code>
     * @return int|string
     */
    public function getOriginId()
    {
        return $this->originId;
    }

    /**
     * Generated from protobuf field <code>int64 originId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOriginId($var)
    {
        GPBUtil::checkInt64($var);
        $this->originId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 startTime = 3;</code>
     * @return int|string
     */
    public function getStartTime()
    {
        return $this->startTime;
    }

    /**
     * Generated from protobuf field <code>int64 startTime = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->startTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 stopTime = 4;</code>
     * @return int|string
     */
    public function getStopTime()
    {
        return $this->stopTime;
    }

    /**
     * Generated from protobuf field <code>int64 stopTime = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStopTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->stopTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 status = 5;</code>
     * @return int|string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>int64 status = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt64($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 page = 6;</code>
     * @return int|string
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * Generated from protobuf field <code>int64 page = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt64($var);
        $this->page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 pageSize = 7;</code>
     * @return int|string
     */
    public function getPageSize()
    {
        return $this->pageSize;
    }

    /**
     * Generated from protobuf field <code>int64 pageSize = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->pageSize = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 id = 8;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

}

