<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Yinge\Grpc\Finance;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finance.WithdrawExportRequest</code>
 */
class WithdrawExportRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 type = 1;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>string dateStart = 2;</code>
     */
    protected $dateStart = '';
    /**
     * Generated from protobuf field <code>string dateEnd = 3;</code>
     */
    protected $dateEnd = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $type
     *     @type string $dateStart
     *     @type string $dateEnd
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Finance\GPBMetadata\Finance::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 type = 1;</code>
     * @return int|string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>int64 type = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt64($var);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string dateStart = 2;</code>
     * @return string
     */
    public function getDateStart()
    {
        return $this->dateStart;
    }

    /**
     * Generated from protobuf field <code>string dateStart = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDateStart($var)
    {
        GPBUtil::checkString($var, True);
        $this->dateStart = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string dateEnd = 3;</code>
     * @return string
     */
    public function getDateEnd()
    {
        return $this->dateEnd;
    }

    /**
     * Generated from protobuf field <code>string dateEnd = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDateEnd($var)
    {
        GPBUtil::checkString($var, True);
        $this->dateEnd = $var;

        return $this;
    }

}

