<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Yinge\Grpc\Finance;

if (false) {
    /**
     * This class is deprecated. Use Yinge\Grpc\Finance\WithdrawListResponse\WithdrawDetail instead.
     * @deprecated
     */
    class WithdrawListResponse_WithdrawDetail {}
}
class_exists(WithdrawListResponse\WithdrawDetail::class);
@trigger_error('Yinge\Grpc\Finance\WithdrawListResponse_WithdrawDetail is deprecated and will be removed in the next major release. Use Yinge\Grpc\Finance\WithdrawListResponse\WithdrawDetail instead', E_USER_DEPRECATED);

