<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Yinge\Grpc\Finance\MerchantListResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Finance.MerchantListResponse.Items</code>
 */
class Items extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Finance.MerchantInfo baseInfo = 1;</code>
     */
    protected $baseInfo = null;
    /**
     * Generated from protobuf field <code>.Finance.MerchantListResponse.Account account = 2;</code>
     */
    protected $account = null;
    /**
     * Generated from protobuf field <code>repeated .Finance.MerchantListResponse.BankBind bankBounded = 3;</code>
     */
    private $bankBounded;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Yinge\Grpc\Finance\MerchantInfo $baseInfo
     *     @type \Yinge\Grpc\Finance\MerchantListResponse\Account $account
     *     @type \Yinge\Grpc\Finance\MerchantListResponse\BankBind[]|\Google\Protobuf\Internal\RepeatedField $bankBounded
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Finance\GPBMetadata\Finance::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Finance.MerchantInfo baseInfo = 1;</code>
     * @return \Yinge\Grpc\Finance\MerchantInfo
     */
    public function getBaseInfo()
    {
        return isset($this->baseInfo) ? $this->baseInfo : null;
    }

    public function hasBaseInfo()
    {
        return isset($this->baseInfo);
    }

    public function clearBaseInfo()
    {
        unset($this->baseInfo);
    }

    /**
     * Generated from protobuf field <code>.Finance.MerchantInfo baseInfo = 1;</code>
     * @param \Yinge\Grpc\Finance\MerchantInfo $var
     * @return $this
     */
    public function setBaseInfo($var)
    {
        GPBUtil::checkMessage($var, \Yinge\Grpc\Finance\MerchantInfo::class);
        $this->baseInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Finance.MerchantListResponse.Account account = 2;</code>
     * @return \Yinge\Grpc\Finance\MerchantListResponse\Account
     */
    public function getAccount()
    {
        return isset($this->account) ? $this->account : null;
    }

    public function hasAccount()
    {
        return isset($this->account);
    }

    public function clearAccount()
    {
        unset($this->account);
    }

    /**
     * Generated from protobuf field <code>.Finance.MerchantListResponse.Account account = 2;</code>
     * @param \Yinge\Grpc\Finance\MerchantListResponse\Account $var
     * @return $this
     */
    public function setAccount($var)
    {
        GPBUtil::checkMessage($var, \Yinge\Grpc\Finance\MerchantListResponse\Account::class);
        $this->account = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Finance.MerchantListResponse.BankBind bankBounded = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBankBounded()
    {
        return $this->bankBounded;
    }

    /**
     * Generated from protobuf field <code>repeated .Finance.MerchantListResponse.BankBind bankBounded = 3;</code>
     * @param \Yinge\Grpc\Finance\MerchantListResponse\BankBind[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBankBounded($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Yinge\Grpc\Finance\MerchantListResponse\BankBind::class);
        $this->bankBounded = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Items::class, \Yinge\Grpc\Finance\MerchantListResponse_Items::class);

