<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: QpmServiceBlock.proto

namespace Yinge\Grpc\QpmServiceBlock;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>QpmServiceBlock.SpuCapacity</code>
 */
class SpuCapacity extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 spuId = 1;</code>
     */
    protected $spuId = 0;
    /**
     * Generated from protobuf field <code>int32 produceCapacity = 2;</code>
     */
    protected $produceCapacity = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $spuId
     *     @type int $produceCapacity
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\QpmServiceBlock\GPBMetadata\QpmServiceBlock::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 spuId = 1;</code>
     * @return int
     */
    public function getSpuId()
    {
        return $this->spuId;
    }

    /**
     * Generated from protobuf field <code>int32 spuId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSpuId($var)
    {
        GPBUtil::checkInt32($var);
        $this->spuId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 produceCapacity = 2;</code>
     * @return int
     */
    public function getProduceCapacity()
    {
        return $this->produceCapacity;
    }

    /**
     * Generated from protobuf field <code>int32 produceCapacity = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setProduceCapacity($var)
    {
        GPBUtil::checkInt32($var);
        $this->produceCapacity = $var;

        return $this;
    }

}

