<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: QpmServiceBlock.proto

namespace Yinge\Grpc\QpmServiceBlock;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>QpmServiceBlock.SpuIdList</code>
 */
class SpuIdList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated int32 spuIdList = 1;</code>
     */
    private $spuIdList;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $spuIdList
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\QpmServiceBlock\GPBMetadata\QpmServiceBlock::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated int32 spuIdList = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSpuIdList()
    {
        return $this->spuIdList;
    }

    /**
     * Generated from protobuf field <code>repeated int32 spuIdList = 1;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSpuIdList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->spuIdList = $arr;

        return $this;
    }

}

