<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vision.proto

namespace Yinge\Grpc\Vision\TPLData;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Vision.TPLData.Mask</code>
 */
class Mask extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string maskUrl = 1;</code>
     */
    protected $maskUrl = '';
    /**
     * Generated from protobuf field <code>string coverUrl = 2;</code>
     */
    protected $coverUrl = '';
    /**
     * Generated from protobuf field <code>string meshUrl = 3;</code>
     */
    protected $meshUrl = '';
    /**
     * Generated from protobuf field <code>int32 direction = 4;</code>
     */
    protected $direction = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $maskUrl
     *     @type string $coverUrl
     *     @type string $meshUrl
     *     @type int $direction
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Vision\GPBMetadata\Vision::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string maskUrl = 1;</code>
     * @return string
     */
    public function getMaskUrl()
    {
        return $this->maskUrl;
    }

    /**
     * Generated from protobuf field <code>string maskUrl = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMaskUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->maskUrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string coverUrl = 2;</code>
     * @return string
     */
    public function getCoverUrl()
    {
        return $this->coverUrl;
    }

    /**
     * Generated from protobuf field <code>string coverUrl = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCoverUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->coverUrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string meshUrl = 3;</code>
     * @return string
     */
    public function getMeshUrl()
    {
        return $this->meshUrl;
    }

    /**
     * Generated from protobuf field <code>string meshUrl = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMeshUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->meshUrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 direction = 4;</code>
     * @return int
     */
    public function getDirection()
    {
        return $this->direction;
    }

    /**
     * Generated from protobuf field <code>int32 direction = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setDirection($var)
    {
        GPBUtil::checkInt32($var);
        $this->direction = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Mask::class, \Yinge\Grpc\Vision\TPLData_Mask::class);

