<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Yinge\Grpc\Finance\WithdrawListResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finance.WithdrawListResponse.WithdrawDetail</code>
 */
class WithdrawDetail extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>.finance.MerchantInfo merchantInfo = 2;</code>
     */
    protected $merchantInfo = null;
    /**
     * Generated from protobuf field <code>int64 amount = 3;</code>
     */
    protected $amount = 0;
    /**
     * Generated from protobuf field <code>int64 status = 4;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>int64 applyAt = 5;</code>
     */
    protected $applyAt = 0;
    /**
     * Generated from protobuf field <code>string remark = 6;</code>
     */
    protected $remark = '';
    /**
     * Generated from protobuf field <code>.finance.BankBind bankBounded = 7;</code>
     */
    protected $bankBounded = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type \Yinge\Grpc\Finance\MerchantInfo $merchantInfo
     *     @type int|string $amount
     *     @type int|string $status
     *     @type int|string $applyAt
     *     @type string $remark
     *     @type \Yinge\Grpc\Finance\BankBind $bankBounded
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Finance\GPBMetadata\Finance::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.finance.MerchantInfo merchantInfo = 2;</code>
     * @return \Yinge\Grpc\Finance\MerchantInfo
     */
    public function getMerchantInfo()
    {
        return $this->merchantInfo;
    }

    /**
     * Generated from protobuf field <code>.finance.MerchantInfo merchantInfo = 2;</code>
     * @param \Yinge\Grpc\Finance\MerchantInfo $var
     * @return $this
     */
    public function setMerchantInfo($var)
    {
        GPBUtil::checkMessage($var, \Yinge\Grpc\Finance\MerchantInfo::class);
        $this->merchantInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 amount = 3;</code>
     * @return int|string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>int64 amount = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 status = 4;</code>
     * @return int|string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>int64 status = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt64($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 applyAt = 5;</code>
     * @return int|string
     */
    public function getApplyAt()
    {
        return $this->applyAt;
    }

    /**
     * Generated from protobuf field <code>int64 applyAt = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setApplyAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->applyAt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string remark = 6;</code>
     * @return string
     */
    public function getRemark()
    {
        return $this->remark;
    }

    /**
     * Generated from protobuf field <code>string remark = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setRemark($var)
    {
        GPBUtil::checkString($var, True);
        $this->remark = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.finance.BankBind bankBounded = 7;</code>
     * @return \Yinge\Grpc\Finance\BankBind
     */
    public function getBankBounded()
    {
        return $this->bankBounded;
    }

    /**
     * Generated from protobuf field <code>.finance.BankBind bankBounded = 7;</code>
     * @param \Yinge\Grpc\Finance\BankBind $var
     * @return $this
     */
    public function setBankBounded($var)
    {
        GPBUtil::checkMessage($var, \Yinge\Grpc\Finance\BankBind::class);
        $this->bankBounded = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(WithdrawDetail::class, \Yinge\Grpc\Finance\WithdrawListResponse_WithdrawDetail::class);

