<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto

namespace Yinge\Grpc\Product;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 属性-参数
 *
 * Generated from protobuf message <code>Product.Attr</code>
 */
class Attr extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 attrId = 1;</code>
     */
    protected $attrId = 0;
    /**
     * Generated from protobuf field <code>string attrName = 2;</code>
     */
    protected $attrName = '';
    /**
     * Generated from protobuf field <code>int64 sort = 3;</code>
     */
    protected $sort = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $attrId
     *     @type string $attrName
     *     @type int|string $sort
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Product\GPBMetadata\Product::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 attrId = 1;</code>
     * @return int|string
     */
    public function getAttrId()
    {
        return $this->attrId;
    }

    /**
     * Generated from protobuf field <code>uint64 attrId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAttrId($var)
    {
        GPBUtil::checkUint64($var);
        $this->attrId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string attrName = 2;</code>
     * @return string
     */
    public function getAttrName()
    {
        return $this->attrName;
    }

    /**
     * Generated from protobuf field <code>string attrName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAttrName($var)
    {
        GPBUtil::checkString($var, True);
        $this->attrName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 sort = 3;</code>
     * @return int|string
     */
    public function getSort()
    {
        return $this->sort;
    }

    /**
     * Generated from protobuf field <code>int64 sort = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSort($var)
    {
        GPBUtil::checkInt64($var);
        $this->sort = $var;

        return $this;
    }

}

