<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto

namespace Yinge\Grpc\Product;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 属性值-参数
 *
 * Generated from protobuf message <code>Product.AttrVal</code>
 */
class AttrVal extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 valId = 3;</code>
     */
    protected $valId = 0;
    /**
     * Generated from protobuf field <code>string valName = 4;</code>
     */
    protected $valName = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $valId
     *     @type string $valName
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Product\GPBMetadata\Product::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 valId = 3;</code>
     * @return int|string
     */
    public function getValId()
    {
        return $this->valId;
    }

    /**
     * Generated from protobuf field <code>uint64 valId = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setValId($var)
    {
        GPBUtil::checkUint64($var);
        $this->valId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string valName = 4;</code>
     * @return string
     */
    public function getValName()
    {
        return $this->valName;
    }

    /**
     * Generated from protobuf field <code>string valName = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setValName($var)
    {
        GPBUtil::checkString($var, True);
        $this->valName = $var;

        return $this;
    }

}

