<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto

namespace Yinge\Grpc\Product;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Product.GetAttrAndValResponse</code>
 */
class GetAttrAndValResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Product.AttrAndValRelation attrAndVal = 1;</code>
     */
    private $attrAndVal;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Yinge\Grpc\Product\AttrAndValRelation[]|\Google\Protobuf\Internal\RepeatedField $attrAndVal
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Product\GPBMetadata\Product::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Product.AttrAndValRelation attrAndVal = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAttrAndVal()
    {
        return $this->attrAndVal;
    }

    /**
     * Generated from protobuf field <code>repeated .Product.AttrAndValRelation attrAndVal = 1;</code>
     * @param \Yinge\Grpc\Product\AttrAndValRelation[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAttrAndVal($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Yinge\Grpc\Product\AttrAndValRelation::class);
        $this->attrAndVal = $arr;

        return $this;
    }

}

