<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto

namespace Yinge\Grpc\Product;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 根据分类id 获取属性与属性值请求
 *
 * Generated from protobuf message <code>Product.GetAttrAndValRequest</code>
 */
class GetAttrAndValRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Product.PageParam pageParam = 1;</code>
     */
    protected $pageParam = null;
    /**
     * Generated from protobuf field <code>uint64 categoryId = 2;</code>
     */
    protected $categoryId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Yinge\Grpc\Product\PageParam $pageParam
     *     @type int|string $categoryId
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Product\GPBMetadata\Product::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Product.PageParam pageParam = 1;</code>
     * @return \Yinge\Grpc\Product\PageParam
     */
    public function getPageParam()
    {
        return isset($this->pageParam) ? $this->pageParam : null;
    }

    public function hasPageParam()
    {
        return isset($this->pageParam);
    }

    public function clearPageParam()
    {
        unset($this->pageParam);
    }

    /**
     * Generated from protobuf field <code>.Product.PageParam pageParam = 1;</code>
     * @param \Yinge\Grpc\Product\PageParam $var
     * @return $this
     */
    public function setPageParam($var)
    {
        GPBUtil::checkMessage($var, \Yinge\Grpc\Product\PageParam::class);
        $this->pageParam = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 categoryId = 2;</code>
     * @return int|string
     */
    public function getCategoryId()
    {
        return $this->categoryId;
    }

    /**
     * Generated from protobuf field <code>uint64 categoryId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCategoryId($var)
    {
        GPBUtil::checkUint64($var);
        $this->categoryId = $var;

        return $this;
    }

}

