<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto

namespace Yinge\Grpc\Product;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Product.Materiel</code>
 */
class Materiel extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 skuId = 1;</code>
     */
    protected $skuId = 0;
    /**
     * Generated from protobuf field <code>string skuName = 2;</code>
     */
    protected $skuName = '';
    /**
     * Generated from protobuf field <code>int64 total = 3;</code>
     */
    protected $total = 0;
    /**
     * Generated from protobuf field <code>string produceCode = 4;</code>
     */
    protected $produceCode = '';
    /**
     * Generated from protobuf field <code>float weight = 6;</code>
     */
    protected $weight = 0.0;
    /**
     * Generated from protobuf field <code>string unit = 7;</code>
     */
    protected $unit = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $skuId
     *     @type string $skuName
     *     @type int|string $total
     *     @type string $produceCode
     *     @type float $weight
     *     @type string $unit
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Product\GPBMetadata\Product::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 skuId = 1;</code>
     * @return int|string
     */
    public function getSkuId()
    {
        return $this->skuId;
    }

    /**
     * Generated from protobuf field <code>uint64 skuId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSkuId($var)
    {
        GPBUtil::checkUint64($var);
        $this->skuId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string skuName = 2;</code>
     * @return string
     */
    public function getSkuName()
    {
        return $this->skuName;
    }

    /**
     * Generated from protobuf field <code>string skuName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSkuName($var)
    {
        GPBUtil::checkString($var, True);
        $this->skuName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 total = 3;</code>
     * @return int|string
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Generated from protobuf field <code>int64 total = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkInt64($var);
        $this->total = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string produceCode = 4;</code>
     * @return string
     */
    public function getProduceCode()
    {
        return $this->produceCode;
    }

    /**
     * Generated from protobuf field <code>string produceCode = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setProduceCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->produceCode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float weight = 6;</code>
     * @return float
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     * Generated from protobuf field <code>float weight = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setWeight($var)
    {
        GPBUtil::checkFloat($var);
        $this->weight = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string unit = 7;</code>
     * @return string
     */
    public function getUnit()
    {
        return $this->unit;
    }

    /**
     * Generated from protobuf field <code>string unit = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setUnit($var)
    {
        GPBUtil::checkString($var, True);
        $this->unit = $var;

        return $this;
    }

}

