<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto

namespace Yinge\Grpc\Product;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * sku 基础参数
 *
 * Generated from protobuf message <code>Product.Sku</code>
 */
class Sku extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 skuId = 1;</code>
     */
    protected $skuId = 0;
    /**
     * Generated from protobuf field <code>uint64 spuId = 2;</code>
     */
    protected $spuId = 0;
    /**
     * Generated from protobuf field <code>string spuName = 3;</code>
     */
    protected $spuName = '';
    /**
     * Generated from protobuf field <code>string skuName = 4;</code>
     */
    protected $skuName = '';
    /**
     * Generated from protobuf field <code>repeated .Product.AttrAndValFlat attrList = 5;</code>
     */
    private $attrList;
    /**
     * 生产编码
     *
     * Generated from protobuf field <code>string produceCode = 6;</code>
     */
    protected $produceCode = '';
    /**
     * Generated from protobuf field <code>uint64 cid = 7;</code>
     */
    protected $cid = 0;
    /**
     * Generated from protobuf field <code>float weight = 8;</code>
     */
    protected $weight = 0.0;
    /**
     * 单位
     *
     * Generated from protobuf field <code>string unit = 9;</code>
     */
    protected $unit = '';
    /**
     * Generated from protobuf field <code>int64 productType = 10;</code>
     */
    protected $productType = 0;
    /**
     * Generated from protobuf field <code>string img = 11;</code>
     */
    protected $img = '';
    /**
     * Generated from protobuf field <code>string length = 12;</code>
     */
    protected $length = '';
    /**
     * Generated from protobuf field <code>string width = 13;</code>
     */
    protected $width = '';
    /**
     * Generated from protobuf field <code>string height = 14;</code>
     */
    protected $height = '';
    /**
     * Generated from protobuf field <code>bool isDeleted = 15;</code>
     */
    protected $isDeleted = false;
    /**
     * Generated from protobuf field <code>string skuCode = 16;</code>
     */
    protected $skuCode = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $skuId
     *     @type int|string $spuId
     *     @type string $spuName
     *     @type string $skuName
     *     @type \Yinge\Grpc\Product\AttrAndValFlat[]|\Google\Protobuf\Internal\RepeatedField $attrList
     *     @type string $produceCode
     *           生产编码
     *     @type int|string $cid
     *     @type float $weight
     *     @type string $unit
     *           单位
     *     @type int|string $productType
     *     @type string $img
     *     @type string $length
     *     @type string $width
     *     @type string $height
     *     @type bool $isDeleted
     *     @type string $skuCode
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Product\GPBMetadata\Product::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 skuId = 1;</code>
     * @return int|string
     */
    public function getSkuId()
    {
        return $this->skuId;
    }

    /**
     * Generated from protobuf field <code>uint64 skuId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSkuId($var)
    {
        GPBUtil::checkUint64($var);
        $this->skuId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 spuId = 2;</code>
     * @return int|string
     */
    public function getSpuId()
    {
        return $this->spuId;
    }

    /**
     * Generated from protobuf field <code>uint64 spuId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSpuId($var)
    {
        GPBUtil::checkUint64($var);
        $this->spuId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string spuName = 3;</code>
     * @return string
     */
    public function getSpuName()
    {
        return $this->spuName;
    }

    /**
     * Generated from protobuf field <code>string spuName = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSpuName($var)
    {
        GPBUtil::checkString($var, True);
        $this->spuName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string skuName = 4;</code>
     * @return string
     */
    public function getSkuName()
    {
        return $this->skuName;
    }

    /**
     * Generated from protobuf field <code>string skuName = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSkuName($var)
    {
        GPBUtil::checkString($var, True);
        $this->skuName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Product.AttrAndValFlat attrList = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAttrList()
    {
        return $this->attrList;
    }

    /**
     * Generated from protobuf field <code>repeated .Product.AttrAndValFlat attrList = 5;</code>
     * @param \Yinge\Grpc\Product\AttrAndValFlat[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAttrList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Yinge\Grpc\Product\AttrAndValFlat::class);
        $this->attrList = $arr;

        return $this;
    }

    /**
     * 生产编码
     *
     * Generated from protobuf field <code>string produceCode = 6;</code>
     * @return string
     */
    public function getProduceCode()
    {
        return $this->produceCode;
    }

    /**
     * 生产编码
     *
     * Generated from protobuf field <code>string produceCode = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setProduceCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->produceCode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 cid = 7;</code>
     * @return int|string
     */
    public function getCid()
    {
        return $this->cid;
    }

    /**
     * Generated from protobuf field <code>uint64 cid = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCid($var)
    {
        GPBUtil::checkUint64($var);
        $this->cid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float weight = 8;</code>
     * @return float
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     * Generated from protobuf field <code>float weight = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setWeight($var)
    {
        GPBUtil::checkFloat($var);
        $this->weight = $var;

        return $this;
    }

    /**
     * 单位
     *
     * Generated from protobuf field <code>string unit = 9;</code>
     * @return string
     */
    public function getUnit()
    {
        return $this->unit;
    }

    /**
     * 单位
     *
     * Generated from protobuf field <code>string unit = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setUnit($var)
    {
        GPBUtil::checkString($var, True);
        $this->unit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 productType = 10;</code>
     * @return int|string
     */
    public function getProductType()
    {
        return $this->productType;
    }

    /**
     * Generated from protobuf field <code>int64 productType = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setProductType($var)
    {
        GPBUtil::checkInt64($var);
        $this->productType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string img = 11;</code>
     * @return string
     */
    public function getImg()
    {
        return $this->img;
    }

    /**
     * Generated from protobuf field <code>string img = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setImg($var)
    {
        GPBUtil::checkString($var, True);
        $this->img = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string length = 12;</code>
     * @return string
     */
    public function getLength()
    {
        return $this->length;
    }

    /**
     * Generated from protobuf field <code>string length = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setLength($var)
    {
        GPBUtil::checkString($var, True);
        $this->length = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string width = 13;</code>
     * @return string
     */
    public function getWidth()
    {
        return $this->width;
    }

    /**
     * Generated from protobuf field <code>string width = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setWidth($var)
    {
        GPBUtil::checkString($var, True);
        $this->width = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string height = 14;</code>
     * @return string
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * Generated from protobuf field <code>string height = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkString($var, True);
        $this->height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isDeleted = 15;</code>
     * @return bool
     */
    public function getIsDeleted()
    {
        return $this->isDeleted;
    }

    /**
     * Generated from protobuf field <code>bool isDeleted = 15;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDeleted($var)
    {
        GPBUtil::checkBool($var);
        $this->isDeleted = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string skuCode = 16;</code>
     * @return string
     */
    public function getSkuCode()
    {
        return $this->skuCode;
    }

    /**
     * Generated from protobuf field <code>string skuCode = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setSkuCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->skuCode = $var;

        return $this;
    }

}

