<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto

namespace Yinge\Grpc\Product;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Product.SkuBaseRequest</code>
 */
class SkuBaseRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 spuId = 1;</code>
     */
    protected $spuId = 0;
    /**
     * Generated from protobuf field <code>string keyword = 2;</code>
     */
    protected $keyword = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $spuId
     *     @type string $keyword
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Product\GPBMetadata\Product::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 spuId = 1;</code>
     * @return int|string
     */
    public function getSpuId()
    {
        return $this->spuId;
    }

    /**
     * Generated from protobuf field <code>int64 spuId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSpuId($var)
    {
        GPBUtil::checkInt64($var);
        $this->spuId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string keyword = 2;</code>
     * @return string
     */
    public function getKeyword()
    {
        return $this->keyword;
    }

    /**
     * Generated from protobuf field <code>string keyword = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setKeyword($var)
    {
        GPBUtil::checkString($var, True);
        $this->keyword = $var;

        return $this;
    }

}

