<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto

namespace Yinge\Grpc\Product;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Product.SkuDetailRep</code>
 */
class SkuDetailRep extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Product.Sku skuInfo = 1;</code>
     */
    private $skuInfo;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Yinge\Grpc\Product\Sku[]|\Google\Protobuf\Internal\RepeatedField $skuInfo
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Product\GPBMetadata\Product::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Product.Sku skuInfo = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSkuInfo()
    {
        return $this->skuInfo;
    }

    /**
     * Generated from protobuf field <code>repeated .Product.Sku skuInfo = 1;</code>
     * @param \Yinge\Grpc\Product\Sku[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSkuInfo($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Yinge\Grpc\Product\Sku::class);
        $this->skuInfo = $arr;

        return $this;
    }

}

