<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto

namespace Yinge\Grpc\Product;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * spu 基础参数
 *
 * Generated from protobuf message <code>Product.Spu</code>
 */
class Spu extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 spuId = 1;</code>
     */
    protected $spuId = 0;
    /**
     * Generated from protobuf field <code>string spuName = 2;</code>
     */
    protected $spuName = '';
    /**
     * Generated from protobuf field <code>uint64 categoryId = 3;</code>
     */
    protected $categoryId = 0;
    /**
     * Generated from protobuf field <code>string categoryName = 4;</code>
     */
    protected $categoryName = '';
    /**
     * Generated from protobuf field <code>string shortName = 5;</code>
     */
    protected $shortName = '';
    /**
     * Generated from protobuf field <code>uint64 skuCount = 6;</code>
     */
    protected $skuCount = 0;
    /**
     * Generated from protobuf field <code>repeated .Product.AttrAndValRelation attrList = 7;</code>
     */
    private $attrList;
    /**
     * Generated from protobuf field <code>int64 productType = 8;</code>
     */
    protected $productType = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $spuId
     *     @type string $spuName
     *     @type int|string $categoryId
     *     @type string $categoryName
     *     @type string $shortName
     *     @type int|string $skuCount
     *     @type \Yinge\Grpc\Product\AttrAndValRelation[]|\Google\Protobuf\Internal\RepeatedField $attrList
     *     @type int|string $productType
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Product\GPBMetadata\Product::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 spuId = 1;</code>
     * @return int|string
     */
    public function getSpuId()
    {
        return $this->spuId;
    }

    /**
     * Generated from protobuf field <code>uint64 spuId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSpuId($var)
    {
        GPBUtil::checkUint64($var);
        $this->spuId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string spuName = 2;</code>
     * @return string
     */
    public function getSpuName()
    {
        return $this->spuName;
    }

    /**
     * Generated from protobuf field <code>string spuName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSpuName($var)
    {
        GPBUtil::checkString($var, True);
        $this->spuName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 categoryId = 3;</code>
     * @return int|string
     */
    public function getCategoryId()
    {
        return $this->categoryId;
    }

    /**
     * Generated from protobuf field <code>uint64 categoryId = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCategoryId($var)
    {
        GPBUtil::checkUint64($var);
        $this->categoryId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string categoryName = 4;</code>
     * @return string
     */
    public function getCategoryName()
    {
        return $this->categoryName;
    }

    /**
     * Generated from protobuf field <code>string categoryName = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCategoryName($var)
    {
        GPBUtil::checkString($var, True);
        $this->categoryName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string shortName = 5;</code>
     * @return string
     */
    public function getShortName()
    {
        return $this->shortName;
    }

    /**
     * Generated from protobuf field <code>string shortName = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setShortName($var)
    {
        GPBUtil::checkString($var, True);
        $this->shortName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 skuCount = 6;</code>
     * @return int|string
     */
    public function getSkuCount()
    {
        return $this->skuCount;
    }

    /**
     * Generated from protobuf field <code>uint64 skuCount = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSkuCount($var)
    {
        GPBUtil::checkUint64($var);
        $this->skuCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Product.AttrAndValRelation attrList = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAttrList()
    {
        return $this->attrList;
    }

    /**
     * Generated from protobuf field <code>repeated .Product.AttrAndValRelation attrList = 7;</code>
     * @param \Yinge\Grpc\Product\AttrAndValRelation[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAttrList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Yinge\Grpc\Product\AttrAndValRelation::class);
        $this->attrList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 productType = 8;</code>
     * @return int|string
     */
    public function getProductType()
    {
        return $this->productType;
    }

    /**
     * Generated from protobuf field <code>int64 productType = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setProductType($var)
    {
        GPBUtil::checkInt64($var);
        $this->productType = $var;

        return $this;
    }

}

