<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto

namespace Yinge\Grpc\Product;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 第三方sku请求
 *
 * Generated from protobuf message <code>Product.ThirdPartySkuRequest</code>
 */
class ThirdPartySkuRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string skuName = 1;</code>
     */
    protected $skuName = '';
    /**
     * Generated from protobuf field <code>string spuName = 2;</code>
     */
    protected $spuName = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $skuName
     *     @type string $spuName
     * }
     */
    public function __construct($data = NULL) {
        \Yinge\Grpc\Product\GPBMetadata\Product::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string skuName = 1;</code>
     * @return string
     */
    public function getSkuName()
    {
        return $this->skuName;
    }

    /**
     * Generated from protobuf field <code>string skuName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSkuName($var)
    {
        GPBUtil::checkString($var, True);
        $this->skuName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string spuName = 2;</code>
     * @return string
     */
    public function getSpuName()
    {
        return $this->spuName;
    }

    /**
     * Generated from protobuf field <code>string spuName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSpuName($var)
    {
        GPBUtil::checkString($var, True);
        $this->spuName = $var;

        return $this;
    }

}

